import {
  learningModuleId,
  learningPathId,
  lessonId,
  type LearningPathSeed,
  type LessonSeed,
  type ModuleSeed,
  type MODULE_CATEGORIES,
  type MODULE_DIFFICULTIES,
} from "../../src/lib/learning";
import type { Role } from "../../src/lib/enums";

type Category = (typeof MODULE_CATEGORIES)[number];
type ModuleDifficulty = (typeof MODULE_DIFFICULTIES)[number];
type ModuleSpec = {
  slug: string;
  title: string;
  category: Category;
  difficulty?: ModuleDifficulty;
  hours?: number;
  prerequisites?: string[];
};

// This seed-only factory intentionally uses the curriculum noun "module".
// eslint-disable-next-line @next/next/no-assign-module-variable
const module = (
  slug: string,
  title: string,
  category: Category,
  difficulty: ModuleDifficulty = "intermediate",
  prerequisites: string[] = []
): ModuleSpec => ({ slug, title, category, difficulty, prerequisites, hours: difficulty === "advanced" ? 5 : 3 });

const MODULE_SPECS: ModuleSpec[] = [
  // DSA confidence roadmap
  module("arrays-hashmaps-two-pointers", "Arrays, Hashmaps, and Two-Pointers", "dsa", "beginner"),
  module("sliding-window-prefix-sums", "Sliding Window and Prefix Sums", "dsa", "beginner", ["arrays-hashmaps-two-pointers"]),
  module("binary-search", "Binary Search and Boundary Invariants", "dsa", "beginner", ["arrays-hashmaps-two-pointers"]),
  module("linked-lists", "Linked Lists and Pointer Discipline", "dsa", "beginner"),
  module("stacks-queues-heaps", "Stacks, Queues, and Heaps", "dsa", "intermediate", ["arrays-hashmaps-two-pointers"]),
  module("trees-graphs", "Trees and Graphs", "dsa", "intermediate", ["stacks-queues-heaps"]),
  module("tries", "Tries and Prefix Structures", "dsa", "intermediate", ["trees-graphs"]),
  module("backtracking", "Backtracking and Pruned Search", "dsa", "intermediate", ["trees-graphs"]),
  module("greedy", "Greedy Algorithms and Exchange Arguments", "dsa", "intermediate", ["arrays-hashmaps-two-pointers"]),
  module("intervals", "Intervals and Sweep Lines", "dsa", "intermediate", ["greedy"]),
  module("dynamic-programming-basics", "Dynamic Programming Basics", "dsa", "intermediate", ["arrays-hashmaps-two-pointers"]),
  module("dp-grids-strings", "Dynamic Programming on Grids and Strings", "dsa", "advanced", ["dynamic-programming-basics"]),
  module("advanced-graphs", "Advanced Graphs: Shortest Paths and Ordering", "dsa", "advanced", ["trees-graphs"]),
  module("bit-manipulation", "Bit Manipulation", "dsa", "intermediate", ["arrays-hashmaps-two-pointers"]),
  module("math-geometry", "Math and Geometry for Interviews", "dsa", "intermediate", ["arrays-hashmaps-two-pointers"]),
  module("dsa-to-real-systems", "From DSA to Real Systems", "dsa", "advanced", ["trees-graphs", "dynamic-programming-basics"]),

  // DevOps / infrastructure
  module("docker-fundamentals", "Docker Fundamentals", "docker", "beginner"),
  module("dockerfiles-image-layers", "Dockerfiles and Image Layers", "docker", "intermediate", ["docker-fundamentals"]),
  module("docker-compose", "Docker Compose", "docker", "beginner", ["docker-fundamentals"]),
  module("kubernetes-fundamentals", "Kubernetes Fundamentals", "kubernetes", "beginner", ["docker-fundamentals"]),
  module("pods-deployments-services", "Pods, Deployments, and Services", "kubernetes", "beginner", ["kubernetes-fundamentals"]),
  module("kubernetes-configmaps-secrets", "Kubernetes ConfigMaps and Secrets", "kubernetes", "intermediate", ["pods-deployments-services"]),
  module("kubernetes-networking-ingress", "Kubernetes Networking and Ingress", "kubernetes", "advanced", ["pods-deployments-services", "tcp-vs-udp"]),
  module("kubernetes-scheduling-resource-limits", "Kubernetes Scheduling and Resource Limits", "kubernetes", "advanced", ["pods-deployments-services", "scheduling-context-switching"]),

  // Operating systems
  module("processes-vs-threads", "Processes vs Threads", "operating_systems", "beginner"),
  module("threading-synchronization", "Threading and Synchronization", "concurrency", "intermediate", ["processes-vs-threads"]),
  module("mutexes-semaphores-condition-variables", "Mutexes, Semaphores, and Condition Variables", "concurrency", "intermediate", ["threading-synchronization"]),
  module("deadlocks-starvation", "Deadlocks and Starvation", "concurrency", "advanced", ["mutexes-semaphores-condition-variables"]),
  module("virtual-memory-page-tables", "Virtual Memory and Page Tables", "operating_systems", "intermediate", ["processes-vs-threads"]),
  module("scheduling-context-switching", "Scheduling and Context Switching", "operating_systems", "intermediate", ["processes-vs-threads"]),
  module("filesystems-file-descriptors", "Filesystems and File Descriptors", "operating_systems", "intermediate", ["processes-vs-threads"]),

  // Networking
  module("tcp-vs-udp", "TCP vs UDP", "networking", "beginner"),
  module("sockets-connection-lifecycle", "Sockets and Connection Lifecycle", "networking", "intermediate", ["tcp-vs-udp"]),
  module("http-request-lifecycle", "HTTP Request Lifecycle", "backend", "beginner", ["tcp-vs-udp"]),
  module("load-balancing", "Load Balancing", "infrastructure", "intermediate", ["http-request-lifecycle"]),
  module("dns-fundamentals", "DNS Fundamentals", "networking", "beginner"),
  module("tls-basics", "TLS Basics", "networking", "intermediate", ["tcp-vs-udp"]),
  module("websockets-streaming", "WebSockets and Streaming", "networking", "intermediate", ["http-request-lifecycle"]),

  // C++
  module("raii-resource-ownership", "C++ RAII and Resource Ownership", "cpp", "beginner"),
  module("move-semantics", "C++ Move Semantics", "cpp", "intermediate", ["raii-resource-ownership"]),
  module("references-pointers-lifetimes", "C++ References, Pointers, and Lifetimes", "cpp", "intermediate", ["raii-resource-ownership"]),
  module("stl-containers-iterators", "C++ STL Containers and Iterators", "cpp", "intermediate"),
  module("unordered-map-hashing-collisions", "C++ unordered_map Hashing and Collisions", "cpp", "intermediate", ["stl-containers-iterators"]),
  module("cpp-templates-basics", "C++ Templates Basics", "cpp", "intermediate"),
  module("concurrency-in-cpp", "Concurrency in C++", "cpp", "advanced", ["threading-synchronization", "raii-resource-ownership"]),

  // Python
  module("python-mutability-identity", "Python Mutability and Identity", "python", "beginner"),
  module("python-generators-iterators", "Python Generators and Iterators", "python", "intermediate"),
  module("python-decorators-closures", "Python Decorators and Closures", "python", "intermediate"),
  module("python-gil-concurrency", "Python GIL and Concurrency", "python", "advanced", ["threading-synchronization"]),
  module("python-hashing-equality", "Python Hashing and Equality", "python", "intermediate"),
  module("python-memory-object-model", "Python Memory and Object Model", "python", "advanced", ["python-mutability-identity"]),

  // Databases and caching
  module("sql-indexes", "SQL Indexes", "databases", "beginner"),
  module("composite-indexes", "Composite Indexes", "databases", "intermediate", ["sql-indexes"]),
  module("transactions-isolation", "Transactions and Isolation", "databases", "intermediate"),
  module("query-plans", "Query Plans", "databases", "intermediate", ["sql-indexes"]),
  module("n-plus-one-queries", "N+1 Queries", "databases", "beginner"),
  module("cursor-pagination", "Cursor Pagination", "databases", "intermediate", ["sql-indexes"]),
  module("database-deadlocks-idempotency", "Database Deadlocks and Idempotency", "databases", "advanced", ["transactions-isolation"]),
  module("redis-caching", "Redis and Caching", "caching", "beginner"),

  // System design and backend
  module("system-design-interview-framework", "System Design Interview Framework", "system_design", "beginner"),
  module("apis-requirements", "APIs and Requirements", "system_design", "beginner", ["http-request-lifecycle"]),
  module("rate-limiting", "Rate Limiting", "system_design", "intermediate", ["apis-requirements"]),
  module("caching-strategies", "Caching Strategies", "caching", "intermediate", ["redis-caching"]),
  module("queues-workers", "Queues and Workers", "distributed_systems", "intermediate"),
  module("replication-sharding", "Replication and Sharding", "distributed_systems", "advanced", ["transactions-isolation"]),
  module("observability", "Observability", "infrastructure", "intermediate"),
  module("reliability-backpressure", "Reliability and Backpressure", "distributed_systems", "advanced", ["queues-workers", "observability"]),

  // Quant dev
  module("market-data-feeds", "Market Data Feeds", "quant_dev", "intermediate", ["tcp-vs-udp"]),
  module("order-books", "Order Books", "quant_dev", "intermediate", ["market-data-feeds"]),
  module("latency-cache-locality", "Latency and Cache Locality", "quant_dev", "advanced", ["raii-resource-ownership"]),
  module("linux-for-quant-dev", "Linux for Quant Dev", "quant_dev", "intermediate", ["processes-vs-threads"]),
  module("networking-for-quant-dev", "Networking for Quant Dev", "quant_dev", "advanced", ["tcp-vs-udp", "sockets-connection-lifecycle"]),
  module("concurrency-for-quant-dev", "Concurrency for Quant Dev", "quant_dev", "advanced", ["threading-synchronization"]),

  // AI usage
  module("good-ai-usage-principles", "Good AI Usage Principles", "ai_usage", "beginner"),
  module("token-efficient-prompting", "Token-Efficient Prompting", "ai_usage", "beginner", ["good-ai-usage-principles"]),
  module("selecting-repo-context", "Selecting Repo Context", "ai_usage", "beginner", ["good-ai-usage-principles"]),
  module("reviewing-ai-code", "Reviewing AI Code", "ai_usage", "intermediate", ["selecting-repo-context"]),
  module("hallucination-detection", "Hallucination Detection", "ai_usage", "intermediate", ["reviewing-ai-code"]),
  module("testing-verification", "Test-First AI Workflows", "ai_usage", "intermediate", ["reviewing-ai-code"]),
];

type RealLesson = Omit<LessonSeed, "id" | "order">;
const real = (input: RealLesson): RealLesson => input;

const REAL_LESSONS: Record<string, RealLesson[]> = {
  "arrays-hashmaps-two-pointers": [real({ slug: "two-sum-hashmap-pattern", title: "Two Sum as a Hashmap Pattern", lessonType: "pattern", difficulty: "easy", estimatedMinutes: 15, contentMarkdown: "## Core pattern\n\nFor a pair satisfying `a + b = target`, each value reveals the complement to seek. Scan once, check a hashmap before inserting, and keep the invariant that the map contains only earlier values.\n\n## Interview value\n\nThis tests time-space tradeoffs, duplicate handling, and whether you can explain why one pass is correct.\n\n## Common mistakes\n\nInserting before checking can self-match; returning values instead of indices violates many contracts.\n\n## Next step\n\nCompare the hashmap solution with two pointers on sorted input.", keyTakeaways: ["Use complements to replace pair enumeration with lookup.", "State the one-pass invariant before coding."], examples: ["For `[2, 7, 11]` and target 9, value 7 finds the earlier complement 2."], linkedProblemSlugs: ["pair-sum-request-ids", "quadratic-settlement-matcher"], sourceUrls: ["https://docs.python.org/3/tutorial/datastructures.html#dictionaries"], isPlaceholder: false })],
  "binary-search": [
    real({ slug: "binary-search-invariant", title: "Binary Search as an Invariant Game", lessonType: "concept", difficulty: "easy", estimatedMinutes: 15, contentMarkdown: "## The bracket invariant\n\nBinary search maintains a bracket `[lo, hi]` that provably contains the answer if one exists. Each step computes `mid = lo + (hi - lo) // 2`, asks one question about `mid`, and discards the half that cannot contain the answer. The loop ends when the bracket is empty (`lo > hi`) or collapses to one candidate.\n\n## Why interviewers ask it\n\nAlmost everyone can describe binary search; far fewer can write one whose boundaries are correct on the first try. Interviewers watch whether you state the invariant (\"the answer, if present, is always inside `[lo, hi]`\"), whether the bracket shrinks every iteration, and how you handle the empty array and the not-found case.\n\n## Exact match vs boundary\n\nTwo shapes cover most interview uses:\n\n1. **Exact match** — return `mid` when `values[mid] == target`, otherwise discard the impossible half; return a sentinel when the bracket empties.\n2. **First true** — the input looks like `false, false, …, true, true` under some predicate, and you want the first `true`. Keep `hi` on a known-`true` (or out-of-range) position and `lo` on the first still-possible position; loop `while lo < hi` and never skip `mid` itself when it might be the answer.\n\n## Common mistakes\n\nComputing `mid = (lo + hi) // 2` overflows in fixed-width languages (use `lo + (hi - lo) // 2`); writing `lo = mid` in a first-true search loops forever when `hi - lo == 1`; forgetting that an empty array must return the sentinel before any comparison.\n\n## Next step\n\nWork the warmups below, then the walkthrough lesson that turns feasibility questions into first-true searches.", keyTakeaways: ["State the bracket invariant out loud before writing the loop.", "Every iteration must strictly shrink the bracket, or the loop cannot terminate.", "Exact-match and first-true searches use different loop conditions; know both shapes."], examples: ["In `[3, 7, 9, 14]` searching 9: bracket [0,3], mid 1 (7 < 9) → [2,3], mid 2 (9 == 9) → return index 2."], linkedProblemSlugs: ["sorted-build-id-lookup", "first-failing-canary", "error-code-range-scan"], sourceUrls: ["https://docs.python.org/3/library/bisect.html", "https://en.wikipedia.org/wiki/Binary_search_algorithm"], isPlaceholder: false }),
    real({ slug: "binary-search-on-answers", title: "Searching the Answer Space", lessonType: "walkthrough", difficulty: "medium", estimatedMinutes: 20, contentMarkdown: "## From arrays to answers\n\nBinary search does not need an array — it needs a *monotone question*. If \"is capacity `c` enough?\" is false for small `c` and true for every larger `c`, the smallest sufficient capacity is a first-true boundary, and you can binary search candidate answers instead of indices.\n\n## Worked example\n\nSuppose nightly archives of sizes `[6, 3, 5, 5]` GB must be uploaded, in order, within 3 nights, and each night uploads a contiguous run limited by capacity `c`.\n\n1. **Feasibility check:** given `c`, greedily pack archives into the current night until adding one would exceed `c`, then start a new night. Count nights used. This is O(n) and is the *question* we ask about each candidate.\n2. **Bounds:** any workable `c` is at least `max(sizes)` = 6 (the largest single archive must fit) and never needs to exceed `sum(sizes)` = 19 (one night takes everything).\n3. **Search:** try `c = 12` → 2 nights, feasible, so shrink right: bracket [6, 12]. Try `c = 9` → nights {6,3}, {5}, wait — {6,3}=9, {5,5}=10 > 9 → {5}, {5} = 3 nights, feasible → [6, 9]. Try `c = 7` → {6}, {3}, {5}, {5} = 4 nights, infeasible → [8, 9]. Try `c = 8` → {6}, {3,5}, {5} = 3 nights, feasible → answer 8.\n\n## Why interviewers ask it\n\nThis pattern tests whether you can (a) spot monotonicity, (b) write a clean feasibility function, and (c) keep the boundary search correct. It also mirrors real capacity-planning questions.\n\n## Common mistakes\n\nSearching a non-monotone space (the halving argument silently breaks); setting `lo = 0` instead of `max(sizes)` and returning an answer no single item fits into; off-by-one at the feasible/infeasible boundary.\n\n## Next step\n\nSolve the bandwidth planner core problem, then the applied metric-lookup variant that returns to plain sorted arrays in a production setting.", keyTakeaways: ["Binary search generalizes from sorted arrays to any monotone predicate.", "The feasibility check is a separate function; get it right before searching.", "Derive tight lower/upper bounds from the problem, not from zero and infinity."], examples: ["Minimum nightly capacity for sizes [6,3,5,5] within 3 nights is 8: {6}, {3,5}, {5}."], linkedProblemSlugs: ["backup-bandwidth-planner", "stale-metric-lookup"], sourceUrls: ["https://en.wikipedia.org/wiki/Binary_search_algorithm", "https://docs.python.org/3/library/bisect.html"], isPlaceholder: false }),
  ],
  "linked-lists": [
    real({ slug: "linked-list-pointer-discipline", title: "Linked Lists and Pointer Discipline", lessonType: "concept", difficulty: "easy", estimatedMinutes: 15, contentMarkdown: "## What a linked list buys you\n\nA singly linked list is a chain of nodes, each holding a value and a `next` reference. Unlike an array, inserting or removing a node next to one you already hold is O(1) — but reaching a position is O(n), and only forward movement is possible. Interview problems test whether you can rearrange the chain *without losing it*.\n\n## The three-pointer walk\n\nMost pointer surgery uses the same skeleton: `prev` (already-processed part), `curr` (node being examined), and a saved `nxt = curr.next` taken **before** any pointer is overwritten. Reversal, deletion, and splicing are all variations on this walk.\n\n## The dummy head\n\nOperations that might change the first node (delete head, insert before head) get much simpler with a sentinel node placed in front: `dummy.next = head`. You then always operate on `some_node.next`, never on a special-cased `head` variable, and return `dummy.next` at the end.\n\n## Why interviewers ask it\n\nLinked-list questions are short to state and expose exactly how carefully you sequence mutations. Losing the rest of the chain by overwriting `next` too early is the single most common failure, followed by head/tail edge cases.\n\n## Common mistakes\n\nOverwriting `curr.next` before saving it; special-casing the head instead of using a dummy node; forgetting to terminate the new tail with `None`/`null` after a rearrangement; testing only length-3 lists and missing the empty and single-node cases.\n\n## Next step\n\nDo the reversal warmup, then the slow/fast walkthrough lesson.", keyTakeaways: ["Save `next` before you overwrite it — every pointer bug is a variation of violating this.", "A dummy head removes head-mutation special cases.", "Know the prev/curr/next walk cold; reversal and deletion are the same skeleton."], examples: ["Reversing 1→2→3: after one step prev=1, curr=2; after two steps prev=2→1, curr=3; finish with prev=3→2→1."], linkedProblemSlugs: ["reverse-approval-chain", "merge-alert-feeds"], sourceUrls: ["https://en.wikipedia.org/wiki/Linked_list"], isPlaceholder: false }),
    real({ slug: "slow-fast-pointer-walkthrough", title: "Slow and Fast Pointers, Worked Through", lessonType: "walkthrough", difficulty: "easy", estimatedMinutes: 18, contentMarkdown: "## Two speeds, one pass\n\nMany linked-list questions that look like they need the length first — middle node, kth from the end — fall to two pointers moving at different speeds or offsets in a single pass.\n\n## Worked example: middle node\n\nWalk `slow` one step and `fast` two steps per iteration over 1→2→3→4→5. When `fast` runs off the end (`fast is None or fast.next is None`), `slow` sits on 3 — the middle. For an even-length list 1→2→3→4, this loop leaves `slow` on 3, the *second* of the two middles; check which middle the contract wants before coding.\n\n## Worked example: kth from the end\n\nAdvance a `lead` pointer k steps from a dummy head, then move `lead` and `trail` together until `lead` reaches the last node. `trail` now sits just **before** the target, which is exactly where you need to be to unlink it: `trail.next = trail.next.next`. The dummy head makes \"remove the first node\" fall out of the same code path.\n\n## Why interviewers ask it\n\nOffset pointers test whether you can reason about distances between references instead of simulating with extra memory. The follow-up \"do it in one pass\" checks that you know traversal itself is the expensive part.\n\n## Common mistakes\n\nStopping the offset walk one node too early or late (walk it by hand on a 2-node list); moving `fast` two steps without checking `fast.next` first; returning the node *at* the position when the unlink needs the node *before* it.\n\n## Next step\n\nDo the middle-of-queue warmup, then the checkpoint-removal core problem; the merge challenge combines chains with a heap.", keyTakeaways: ["Slow/fast pointers find the middle in one pass; know which middle you return for even lengths.", "For deletions, park the trailing pointer one node before the target.", "Hand-simulate on lists of length 0, 1, and 2 before trusting the loop."], examples: ["kth-from-end with k=2 on 1→2→3→4: lead ends on 4, trail on 2, unlink gives 1→2→4."], linkedProblemSlugs: ["middle-of-release-queue", "drop-stale-checkpoint"], sourceUrls: ["https://en.wikipedia.org/wiki/Linked_list", "https://en.wikipedia.org/wiki/Cycle_detection"], isPlaceholder: false }),
  ],
  "sliding-window-prefix-sums": [real({ slug: "sliding-window-when-it-applies", title: "Sliding Window: When It Applies", lessonType: "pattern", difficulty: "easy", estimatedMinutes: 18, contentMarkdown: "## Recognition\n\nSliding windows fit contiguous ranges whose validity can be maintained as boundaries move. Expand right, update compact state, then shrink left until the invariant is restored.\n\n## Interview value\n\nThe pattern tests invariant design rather than memorization.\n\n## Common mistakes\n\nDo not use it for non-contiguous choices, and remember to remove state when the left edge advances.", keyTakeaways: ["Contiguity and a maintainable invariant are the main signals.", "Monotonic boundaries give the usual linear-time proof."], examples: ["A distinct-client window tracks counts while both pointers move only forward."], linkedProblemSlugs: ["longest-unique-session-streak", "clean-request-window", "sliding-window-rate-check"], sourceUrls: ["https://www.techinterviewhandbook.org/algorithms/array/"], isPlaceholder: false })],
  "dockerfiles-image-layers": [real({ slug: "docker-image-layers-why-they-matter", title: "Docker Image Layers and Why They Matter", lessonType: "concept", difficulty: "easy", estimatedMinutes: 18, contentMarkdown: "## Mental model\n\nEach Dockerfile instruction contributes an immutable layer. Reusable earlier layers improve build caching, while frequently changing inputs should usually be copied later. Multi-stage builds keep compilers and intermediate artifacts out of the runtime image.\n\n## Interview value\n\nInterviewers use layer questions to test reproducibility, cache reasoning, image size, and supply-chain awareness.\n\n## Common mistakes\n\nCopying the whole repository before dependency installation invalidates caches; deleting files in a later layer does not erase bytes from earlier layers.", keyTakeaways: ["Order Dockerfile instructions by stability to preserve cache reuse.", "Use multi-stage builds to separate build and runtime contents."], examples: ["Copy lockfiles, install dependencies, then copy changing application source."], linkedProblemSlugs: [], sourceUrls: ["https://docs.docker.com/get-started/docker-concepts/building-images/understanding-image-layers/"], isPlaceholder: false })],
  "pods-deployments-services": [real({ slug: "kubernetes-pods-deployments-services", title: "Kubernetes Pods vs Deployments vs Services", lessonType: "concept", difficulty: "easy", estimatedMinutes: 20, contentMarkdown: "## Three responsibilities\n\nA Pod is a scheduling unit for tightly coupled containers. A Deployment declares and rolls out a desired replica set. A Service provides a stable discovery and traffic endpoint for a changing set of selected Pods.\n\n## Interview value\n\nThe distinction tests whether you can separate workload lifecycle from networking and discovery.\n\n## Common mistakes\n\nDo not treat a Pod as durable, or a Service as the controller that creates replicas.", keyTakeaways: ["Pods run containers; Deployments manage replica rollout; Services provide stable reachability.", "Selectors connect controllers and traffic to matching Pods."], examples: ["A Deployment replaces a failed web Pod while a Service keeps the client endpoint stable."], linkedProblemSlugs: [], sourceUrls: ["https://kubernetes.io/docs/concepts/workloads/pods/", "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/", "https://kubernetes.io/docs/concepts/services-networking/service/"], isPlaceholder: false })],
  "processes-vs-threads": [real({ slug: "processes-vs-threads-interview-model", title: "Processes vs Threads", lessonType: "concept", difficulty: "easy", estimatedMinutes: 18, contentMarkdown: "## Isolation and sharing\n\nProcesses normally have separate virtual address spaces and explicit IPC boundaries. Threads within one process share memory and resources but retain independent stacks and scheduling state.\n\n## Interview value\n\nThis is the foundation for reasoning about isolation, synchronization, context switching, and failure containment.\n\n## Common mistakes\n\nShared memory is not automatically safe, and process isolation is not absolute without operating-system controls.", keyTakeaways: ["Processes emphasize isolation; threads emphasize shared in-process state.", "Sharing reduces communication overhead but creates synchronization obligations."], examples: ["A thread can pass an object reference directly; separate processes generally need IPC or shared-memory coordination."], linkedProblemSlugs: [], sourceUrls: ["https://man7.org/linux/man-pages/man7/pthreads.7.html"], isPlaceholder: false })],
  "virtual-memory-page-tables": [real({ slug: "page-tables-virtual-memory", title: "Page Tables and Virtual Memory", lessonType: "concept", difficulty: "medium", estimatedMinutes: 22, contentMarkdown: "## Translation\n\nVirtual memory gives each process an address space whose virtual pages map through page tables to physical frames or to non-resident state. The TLB caches recent translations; a page fault transfers control to the kernel when a mapping is absent or disallowed.\n\n## Interview value\n\nThe topic connects memory isolation, allocation, cache behavior, and performance.\n\n## Common mistakes\n\nA TLB miss is not necessarily a page fault, and a page fault is not always disk I/O.", keyTakeaways: ["Page tables encode virtual-to-physical mappings and permissions.", "The TLB accelerates translation; faults let the kernel resolve missing or invalid access."], examples: ["A copy-on-write write fault can allocate a private frame without reading from disk."], linkedProblemSlugs: [], sourceUrls: ["https://pages.cs.wisc.edu/~remzi/OSTEP/vm-paging.pdf"], isPlaceholder: false })],
  "raii-resource-ownership": [real({ slug: "cpp-raii-in-interviews", title: "C++ RAII in Interviews", lessonType: "concept", difficulty: "easy", estimatedMinutes: 20, contentMarkdown: "## Ownership through lifetime\n\nRAII binds resource acquisition to object construction and cleanup to deterministic destruction. It applies to memory, file descriptors, locks, sockets, and transactions—not only smart pointers.\n\n## Interview value\n\nRAII questions reveal whether code remains correct across early returns, exceptions, moves, and partial construction.\n\n## Common mistakes\n\nA moved-from object must remain valid, and raw ownership without a documented owner invites double release or leaks.", keyTakeaways: ["Express one clear owner and let scope drive cleanup.", "Design move and copy behavior to match the resource semantics."], examples: ["A lock guard releases a mutex on every scope exit, including exceptions."], linkedProblemSlugs: ["cpp-moved-handle-double-close"], sourceUrls: ["https://en.cppreference.com/w/cpp/language/raii.html"], isPlaceholder: false })],
  "tcp-vs-udp": [real({ slug: "tcp-vs-udp-backend-quant", title: "TCP vs UDP for Backend and Quant Dev", lessonType: "concept", difficulty: "medium", estimatedMinutes: 20, contentMarkdown: "## Choose transport properties\n\nTCP is an ordered reliable byte stream with congestion control; loss can delay later bytes on that connection. UDP preserves datagram boundaries and supports multicast but leaves loss, reordering, and recovery to the application.\n\n## Interview value\n\nA strong answer connects transport behavior to latency, fanout, correctness, and recovery instead of saying only that UDP is faster.\n\n## Common mistakes\n\nDo not assume UDP cannot be made reliable at the application layer or that TCP orders data across separate connections.", keyTakeaways: ["Transport choice follows correctness, latency, and fanout needs.", "UDP market-data feeds commonly pair sequence detection with a recovery channel."], examples: ["A missing sequence marks an order book stale until replay or snapshot recovery completes."], linkedProblemSlugs: ["multicast-gap-recovery-design", "order-book-sequence-state-machine"], sourceUrls: ["https://www.rfc-editor.org/rfc/rfc9293", "https://www.rfc-editor.org/rfc/rfc768"], isPlaceholder: false })],
  "rate-limiting": [real({ slug: "what-rate-limiter-does", title: "What a Rate Limiter Actually Does", lessonType: "concept", difficulty: "easy", estimatedMinutes: 18, contentMarkdown: "## Purpose\n\nA rate limiter protects a constrained resource by defining a key, time model, burst policy, storage location, and rejection behavior.\n\n## Interview value\n\nThe topic connects API semantics with distributed state and overload control.\n\n## Common mistakes\n\nAvoid choosing a global key for per-user limits or ignoring atomic updates across servers.", keyTakeaways: ["Define the protected resource and key before choosing an algorithm.", "Burst allowance and sustained rate are separate controls."], examples: ["A token bucket allows a short burst while bounding long-run admission."], linkedProblemSlugs: ["token-bucket-limiter-spec", "sliding-window-rate-check"], sourceUrls: ["https://datatracker.ietf.org/doc/html/rfc6585#section-4"], isPlaceholder: false })],
  "caching-strategies": [real({ slug: "cache-warming-stampedes", title: "Cache Warming and Cache Stampedes", lessonType: "concept", difficulty: "medium", estimatedMinutes: 20, contentMarkdown: "## Separate concerns\n\nWarming preloads likely-hot keys; stampede protection controls concurrent misses. Single-flight, stale-while-revalidate, and bounded refresh concurrency address the latter.\n\n## Interview value\n\nThis tests time-based failure reasoning beyond simply naming Redis.\n\n## Common mistakes\n\nTTL jitter does not solve every hot-key stampede, and locks need expiry and failure handling.", keyTakeaways: ["Warming reduces cold starts; single-flight controls duplicate refresh work.", "Staleness policies need explicit freshness bounds."], examples: ["Thousands of reads during one rebuild can duplicate origin work without coordination."], linkedProblemSlugs: ["cache-write-before-commit", "cache-stampede-product-page"], sourceUrls: ["https://en.wikipedia.org/wiki/Cache_stampede"], isPlaceholder: false })],
  "sql-indexes": [
    real({ slug: "btree-index-mental-model", title: "How a B-Tree Index Finds Your Rows", lessonType: "concept", difficulty: "easy", estimatedMinutes: 18, contentMarkdown: "## What an index actually is\n\nA B-tree index is a separate, sorted structure of (key, row-pointer) entries. Because it is sorted, the database can descend a shallow tree to any key in O(log n) page reads, then follow pointers to the table rows. Without a usable index, the only general plan is a sequential scan of every row.\n\n## What B-trees are good at\n\nEquality (`email = ?`), ranges (`created_at >= ?`), sorted output (`ORDER BY key`), and prefix matches (`LIKE 'ada%'`). All of these exploit the sort order. What they cannot help with: predicates that destroy order, like `LIKE '%son'`, `lower(email) = ?` without a matching expression index, or arithmetic on the column.\n\n## Selectivity decides usefulness\n\nAn index earns its keep when the predicate selects a small fraction of rows. `status = 'pending'` over three status values may match a third of a huge table — the planner will often (correctly) prefer a sequential scan, because random-access row fetches are more expensive per row than a straight scan.\n\n## Indexes are not free\n\nEvery INSERT/UPDATE/DELETE must maintain every index on the table, and each index consumes cache space. Index design is workload design: index what your hot queries filter and sort on, and nothing else.\n\n## Why interviewers ask it\n\nIndex questions test whether you reason from the physical access path — pages read, order exploited, rows fetched — rather than reciting \"indexes make queries fast.\"\n\n## Common mistakes\n\nIndexing every column \"just in case\"; expecting an index to help a leading-wildcard search; ignoring that a function around the column disables a plain index.\n\n## Next step\n\nThe walkthrough lesson reads real query plans before and after adding an index.", keyTakeaways: ["A B-tree serves equality, range, prefix, and ordering predicates by exploiting sort order.", "Low-selectivity predicates make the planner skip the index — often correctly.", "Every index taxes every write; index the workload, not the schema."], examples: ["`WHERE email = 'a@b.c'` on a million-row table: unique B-tree lookup reads a handful of pages instead of the whole table."], linkedProblemSlugs: ["pick-index-for-login-lookup", "wildcard-search-no-index"], sourceUrls: ["https://www.postgresql.org/docs/current/indexes-intro.html", "https://www.sqlite.org/queryplanner.html"], isPlaceholder: false }),
    real({ slug: "reading-explain-before-indexing", title: "Reading EXPLAIN Before You Add an Index", lessonType: "walkthrough", difficulty: "medium", estimatedMinutes: 22, contentMarkdown: "## Plan first, index second\n\nAdding an index without reading the plan is guessing. `EXPLAIN` shows the access path the planner chose; `EXPLAIN ANALYZE` runs the query and shows actual row counts and timing.\n\n## Worked example\n\nQuery: `SELECT id, total FROM orders WHERE customer_id = 42 ORDER BY created_at DESC LIMIT 20` on 20M rows.\n\n1. **Before:** the plan shows `Seq Scan on orders (rows=19,833,102) → Sort → Limit`. Two red flags: the scan visits every row, and the sort processes every match just to keep 20.\n2. **Add** `CREATE INDEX orders_customer_created ON orders (customer_id, created_at DESC)`.\n3. **After:** `Index Scan using orders_customer_created (rows=20)` — the index serves both the equality filter and the ordering, so the LIMIT stops the scan after 20 entries. No sort node at all.\n\n## When the planner ignores your index\n\nCheck these before blaming the planner: a function or cast wraps the column (`lower(email)`), the predicate matches too many rows to beat a sequential scan, the column order in a composite index does not match the query shape, or statistics are stale (`ANALYZE` the table).\n\n## Why interviewers ask it\n\n\"The query is slow, here is the plan\" is a realistic on-call artifact. Strong candidates read the plan's row estimates, name the expensive node, and predict the plan the right index produces.\n\n## Common mistakes\n\nReading only timings and not row counts; verifying with `EXPLAIN` but never `EXPLAIN ANALYZE`, so estimate errors go unnoticed; adding an index that duplicates the leading columns of an existing one.\n\n## Next step\n\nDo the low-selectivity and covering-index core problems, then the index-audit challenge.", keyTakeaways: ["Read the plan's node types and row counts before and after any index change.", "An index that matches filter + order can eliminate both the scan and the sort.", "When the index is ignored, suspect wrapped columns, selectivity, column order, or stale statistics."], examples: ["Composite (customer_id, created_at DESC) turns seq-scan + sort of 20M rows into a 20-row index scan."], linkedProblemSlugs: ["order-status-page-crawl", "covering-index-hot-endpoint", "write-amplification-index-audit"], sourceUrls: ["https://www.postgresql.org/docs/current/using-explain.html", "https://www.sqlite.org/eqp.html"], isPlaceholder: false }),
  ],
  "transactions-isolation": [
    real({ slug: "isolation-levels-anomalies", title: "Isolation Levels and the Anomalies They Allow", lessonType: "concept", difficulty: "medium", estimatedMinutes: 22, contentMarkdown: "## Isolation is a contract about interleavings\n\nTransactions promise atomicity and isolation, but full serializability is expensive, so databases offer levels that permit specific anomalies in exchange for concurrency.\n\n## The anomalies to know by name\n\n- **Dirty read:** seeing another transaction's uncommitted write. Barred at every PostgreSQL level.\n- **Non-repeatable read:** re-reading a row inside one transaction and getting a different committed value.\n- **Phantom:** re-running a predicate query and seeing new matching rows.\n- **Lost update:** two read-modify-write cycles where the second overwrite silently discards the first.\n- **Write skew:** two transactions read the same snapshot, write disjoint rows, and jointly break an invariant no single write violates.\n\n## What the standard levels give you\n\n**Read committed** (PostgreSQL's default): each statement sees data committed before that statement; non-repeatable reads, phantoms, and lost updates are all possible across statements. **Repeatable read / snapshot:** the whole transaction reads one snapshot; lost updates on the same row are detected and abort, but write skew across different rows remains possible. **Serializable:** the system guarantees some serial order, aborting transactions whose dependencies could violate it — application code must retry.\n\n## Why interviewers ask it\n\nMost real payment/inventory bugs are isolation bugs. Interviewers check that you can name the anomaly in a described interleaving and pick the cheapest mechanism that excludes it — not that you always answer \"use serializable.\"\n\n## Common mistakes\n\nBelieving transactions alone prevent lost updates at read committed; calling write skew a lost update; choosing serializable without adding retry handling for aborts.\n\n## Next step\n\nThe walkthrough lesson traces a lost update line by line and repairs it three ways.", keyTakeaways: ["Know the five anomalies by name and the level at which each becomes impossible.", "Read committed re-snapshots per statement; repeatable read snapshots per transaction; serializable adds dependency detection plus retries.", "Pick the cheapest mechanism that excludes the anomaly your invariant fears."], examples: ["Snapshot isolation stops lost updates on one row but permits the classic two-doctors write skew across two rows."], linkedProblemSlugs: ["read-committed-status-check", "double-click-refund", "snapshot-isolation-write-skew-oncall"], sourceUrls: ["https://www.postgresql.org/docs/current/transaction-iso.html", "https://www.postgresql.org/docs/current/mvcc-intro.html"], isPlaceholder: false }),
    real({ slug: "lost-update-walkthrough", title: "Walking Through a Lost Update", lessonType: "walkthrough", difficulty: "medium", estimatedMinutes: 20, contentMarkdown: "## The bug that transactions do not fix\n\nA read-modify-write done as two SQL statements is unsafe at read committed even when wrapped in a transaction.\n\n## Worked interleaving\n\nBalance starts at 100. Session A and session B both run: read balance, compute balance - 30 in the application, write the result.\n\n1. A: `SELECT balance` → 100\n2. B: `SELECT balance` → 100\n3. A: `UPDATE accounts SET balance = 70`; commit\n4. B: `UPDATE accounts SET balance = 70`; commit\n\nTwo 30-unit withdrawals, final balance 70: B's write silently discarded A's. No error was raised anywhere.\n\n## Three repairs and when each fits\n\n1. **Push the arithmetic into the statement:** `UPDATE accounts SET balance = balance - 30 WHERE id = ? AND balance >= 30`, then check the affected-row count. One atomic statement, no window. Best default for counters and balances.\n2. **Pessimistic:** `SELECT … FOR UPDATE` before computing, serializing the two sessions on the row lock. Fits multi-statement logic that genuinely needs the value first; watch lock hold time and ordering.\n3. **Optimistic:** carry a version column: `UPDATE … SET balance = ?, version = version + 1 WHERE id = ? AND version = ?`; zero rows affected means retry. Fits low-contention rows and offline edits.\n\n## Why interviewers ask it\n\nThis interleaving hides in checkout, refund, quota, and inventory code everywhere. Interviewers want the exact schedule that loses the update and a deliberate choice among the three repairs, with tradeoffs.\n\n## Common mistakes\n\nAsserting \"it's in a transaction, so it's safe\"; using FOR UPDATE everywhere and creating lock convoys; optimistic retries without a retry limit or backoff.\n\n## Next step\n\nSolve the double-click refund warmup and the inventory oversell core problem, then the snapshot-consistency applied problem.", keyTakeaways: ["A two-statement read-modify-write loses updates at read committed; the interleaving is four lines long.", "Prefer a single guarded UPDATE; escalate to FOR UPDATE or version checks when logic needs more.", "Every repair has an operational cost: locks serialize, optimistic plans retry."], examples: ["`UPDATE accounts SET balance = balance - 30 WHERE id = 7 AND balance >= 30` returning 0 rows means insufficient funds or a concurrent change — either way, nothing was lost."], linkedProblemSlugs: ["double-click-refund", "inventory-oversell-checkout", "report-snapshot-consistency"], sourceUrls: ["https://www.postgresql.org/docs/current/explicit-locking.html", "https://www.postgresql.org/docs/current/transaction-iso.html"], isPlaceholder: false }),
  ],
  "composite-indexes": [real({ slug: "composite-indexes-query-shape", title: "Composite Indexes and Query Shape", lessonType: "optimization", difficulty: "easy", estimatedMinutes: 20, contentMarkdown: "## Start from the query\n\nA composite index follows predicates and ordering. Equality columns usually lead, followed by range or sort columns.\n\n## Interview value\n\nIndex questions test whether you can explain the visited rows, avoided sort, and write cost.\n\n## Common mistakes\n\nSeparate single-column indexes do not automatically preserve a required composite ordering.", keyTakeaways: ["Index order follows equality, range, and ordering needs.", "Verify choices with an actual query plan."], examples: ["`WHERE customer_id = ? ORDER BY created_at DESC` often benefits from `(customer_id, created_at DESC)`."], linkedProblemSlugs: ["recent-orders-index-warmup", "missing-composite-index-orders"], sourceUrls: ["https://www.postgresql.org/docs/current/indexes-multicolumn.html"], isPlaceholder: false })],
  "system-design-interview-framework": [real({ slug: "structure-system-design-answer", title: "How to Structure a System Design Answer", lessonType: "system_design", difficulty: "easy", estimatedMinutes: 22, contentMarkdown: "## Repeatable sequence\n\nClarify users, operations, scale, reliability, and consistency. Define a small API and data model, draw the request flow, deepen bottlenecks, and end with failures, observability, and tradeoffs.\n\n## Interview value\n\nStructure demonstrates prioritization under ambiguity.\n\n## Common mistakes\n\nDo not start capacity math before the workload or name products without explaining the property they provide.", keyTakeaways: ["Requirements determine which tradeoffs matter.", "Reserve time for failures, observability, and recap."], examples: ["Clarify notification channels, delay, ordering, retries, and preferences before selecting queues."], linkedProblemSlugs: ["cache-stampede-product-page", "outbox-publisher-marks-before-send"], sourceUrls: ["https://sre.google/sre-book/table-of-contents/"], isPlaceholder: false })],
  "token-efficient-prompting": [real({ slug: "token-efficient-debugging-prompts", title: "Token-Efficient Debugging Prompts", lessonType: "ai_usage", difficulty: "easy", estimatedMinutes: 16, contentMarkdown: "## Relevant context only\n\nState the observed failure, expected behavior, constraints, entrypoint, relevant contract, and validation command. Let the agent search call sites before pasting unrelated files.\n\n## Interview and work value\n\nGood context selection demonstrates system understanding and produces changes that are easier to review.\n\n## Common mistakes\n\nDo not dump secrets or ask for a fix before requiring evidence for the hypothesis.", keyTakeaways: ["Lead with observable behavior and acceptance checks.", "Use progressive disclosure of repository context."], examples: ["Provide the handler, client wrapper, timeout configuration, focused test, and a call-site search."], linkedProblemSlugs: ["ai-debug-prompt-warmup", "ai-token-efficient-repo-task", "ai-select-files-for-timeout-fix"], sourceUrls: ["https://docs.github.com/en/copilot/customizing-copilot/adding-repository-custom-instructions-for-github-copilot"], isPlaceholder: false })],
};

function placeholderLessons(spec: ModuleSpec, startOrder: number): LessonSeed[] {
  const moduleId = learningModuleId(spec.slug);
  return ["foundations", "applied-checkpoint"].map((suffix, index) => ({
    id: lessonId(moduleId, `${spec.slug}-${suffix}`),
    slug: `${spec.slug}-${suffix}`,
    title: `${spec.title}: ${index === 0 ? "Foundations" : "Applied Checkpoint"}`,
    lessonType: index === 0 ? "concept" : "walkthrough",
    difficulty: index === 0 ? "easy" : "medium",
    estimatedMinutes: index === 0 ? 20 : 25,
    contentMarkdown: `> **Content scaffold**\n\nExpand this ${index === 0 ? "instructional" : "interview checkpoint"} for **${spec.title}** with a concise mental model, realistic example, common mistakes, and self-review questions.`,
    keyTakeaways: [`Explain the core interview vocabulary for ${spec.title}.`, "Apply the idea to one realistic scenario."],
    examples: ["Add one small worked example and one boundary case."],
    linkedProblemSlugs: [],
    sourceUrls: [],
    order: startOrder + index,
    isPlaceholder: true,
  }));
}

export const learningModules: ModuleSeed[] = MODULE_SPECS.map((spec) => {
  const moduleId = learningModuleId(spec.slug);
  const authored = (REAL_LESSONS[spec.slug] ?? []).map((lesson, index): LessonSeed => ({
    ...lesson,
    id: lessonId(moduleId, lesson.slug),
    order: index + 1,
  }));
  return {
    id: moduleId,
    slug: spec.slug,
    title: spec.title,
    description: `A standalone interview module covering the mental models, tradeoffs, and practice expected for ${spec.title.toLowerCase()}.`,
    category: spec.category,
    difficulty: spec.difficulty ?? "intermediate",
    estimatedHours: spec.hours ?? 3,
    prerequisites: spec.prerequisites ?? [],
    outcomes: [`Explain the core ideas behind ${spec.title}.`, "Apply the topic in a realistic interview scenario."],
    sourceUrls: authored.flatMap((lesson) => lesson.sourceUrls),
    isPublished: true,
    isPlaceholder: authored.length === 0,
    lessons: [...authored, ...placeholderLessons(spec, authored.length + 1)],
  };
});

type PathSpec = {
  slug: string;
  title: string;
  description: string;
  targetRoles: Role[];
  difficulty: string;
  estimatedHours: number;
  modules: string[];
};

const PATHS: PathSpec[] = [
  { slug: "dsa-confidence-builder", title: "DSA Confidence Builder", description: "Build confidence from easy algorithm fundamentals into core patterns and applied interview variants.", targetRoles: ["new_grad_swe", "backend_swe", "quant_developer", "mid_level_swe"], difficulty: "beginner-to-advanced", estimatedHours: 60, modules: ["arrays-hashmaps-two-pointers", "sliding-window-prefix-sums", "binary-search", "linked-lists", "stacks-queues-heaps", "trees-graphs", "tries", "backtracking", "greedy", "intervals", "dynamic-programming-basics", "dp-grids-strings", "advanced-graphs", "bit-manipulation", "math-geometry", "dsa-to-real-systems"] },
  { slug: "backend-swe", title: "Backend SWE Path", description: "A curated route through HTTP, data, caching, queues, observability, and reliable service design.", targetRoles: ["backend_swe", "mid_level_swe", "fullstack_swe"], difficulty: "beginner-to-advanced", estimatedHours: 34, modules: ["http-request-lifecycle", "apis-requirements", "sql-indexes", "composite-indexes", "transactions-isolation", "redis-caching", "caching-strategies", "queues-workers", "rate-limiting", "observability", "reliability-backpressure"] },
  { slug: "infrastructure-swe", title: "Infrastructure SWE Path", description: "A systems route through processes, memory, networking, containers, Kubernetes, concurrency, and reliability.", targetRoles: ["infrastructure_swe", "platform_engineer", "distributed_systems_engineer"], difficulty: "intermediate-to-advanced", estimatedHours: 40, modules: ["processes-vs-threads", "virtual-memory-page-tables", "tcp-vs-udp", "sockets-connection-lifecycle", "docker-fundamentals", "dockerfiles-image-layers", "kubernetes-fundamentals", "pods-deployments-services", "threading-synchronization", "observability", "reliability-backpressure"] },
  { slug: "system-design", title: "System Design Path", description: "Use a repeatable design framework, then deepen APIs, caching, messaging, data distribution, and reliability.", targetRoles: ["backend_swe", "infrastructure_swe", "distributed_systems_engineer", "mid_level_swe"], difficulty: "intermediate-to-advanced", estimatedHours: 30, modules: ["system-design-interview-framework", "apis-requirements", "rate-limiting", "caching-strategies", "queues-workers", "replication-sharding", "observability", "reliability-backpressure"] },
  { slug: "quant-dev", title: "Quant Dev Path", description: "Connect C++, operating systems, networking, concurrency, performance, and market-data mechanics.", targetRoles: ["quant_developer", "hft_swe"], difficulty: "intermediate-to-advanced", estimatedHours: 38, modules: ["raii-resource-ownership", "move-semantics", "stl-containers-iterators", "processes-vs-threads", "tcp-vs-udp", "linux-for-quant-dev", "networking-for-quant-dev", "concurrency-for-quant-dev", "latency-cache-locality", "market-data-feeds", "order-books"] },
  { slug: "ai-efficient-engineer", title: "AI-Efficient Engineer Path", description: "Use coding agents with disciplined context selection, review, tests, and interview-appropriate boundaries.", targetRoles: ["backend_swe", "platform_engineer", "infrastructure_swe", "new_grad_swe"], difficulty: "beginner-to-intermediate", estimatedHours: 16, modules: ["good-ai-usage-principles", "token-efficient-prompting", "selecting-repo-context", "reviewing-ai-code", "hallucination-detection", "testing-verification"] },
];

export const learningPaths: LearningPathSeed[] = PATHS.map((path, pathIndex) => ({
  id: learningPathId(path.slug),
  slug: path.slug,
  title: path.title,
  description: path.description,
  targetRoles: path.targetRoles,
  difficulty: path.difficulty,
  estimatedHours: path.estimatedHours,
  order: pathIndex + 1,
  isPublished: true,
  modules: path.modules.map((moduleSlug, index) => ({
    moduleSlug,
    order: index + 1,
    isRequired: index < Math.ceil(path.modules.length * 0.75),
    label: index === 0 ? "warmup" : index >= Math.ceil(path.modules.length * 0.75) ? "advanced" : "core",
  })),
}));
