import { defineProblems, ORIGINAL_NOTE } from "./types";

export const starterAiUsageProblems = defineProblems([
  {
    slug: "ai-token-efficient-repo-task",
    title: "Cut a 40,000-Token Repo Prompt to the Necessary Context",
    type: "ai_usage",
    difficulty: "medium",
    topics: ["prompting", "token-efficiency", "repository-navigation"],
    targetRoles: ["backend_swe", "platform_engineer", "mid_level_swe"],
    companyStyles: ["startup", "big_tech", "infra_heavy"],
    estimatedMinutes: 25,
    prompt: "A developer pastes an entire service into every coding-agent prompt to change one validation rule. Design a compact prompt that gives the agent the observable goal, constraints, likely entrypoint, relevant contract, validation commands, and permission to search for call sites without preloading unrelated files. Explain what you deliberately omit.",
    constraints: "The prompt must remain useful if one guessed file path is wrong. It should protect unrelated behavior and define when the agent should stop.",
    hints: ["Context quality is about the dependency path for the change, not raw repository volume.", "Give references and inspection instructions first; add file contents only when the tool cannot read them."],
    solutionOutline: "State one outcome and non-goals, name the entrypoint and schema/contract if known, ask the agent to inspect the closest analogue and call sites, and list exact validation commands. Tell it to preserve unrelated changes and stop after the narrow slice. Omit generated files, vendored code, broad logs, and unrelated components. If the first inspection reveals another boundary, add only that context. Evaluate success by correctness and verification, not minimum token count alone.",
    commonMistakes: ["Removing constraints and validation along with excess code, producing a short but ambiguous prompt.", "Guessing every relevant file up front instead of letting repository search confirm the dependency path."],
    followUpQuestions: ["When is pasting a complete minimal reproduction better than pointing at repository files?", "How would you structure a follow-up after the first agent response reveals a missing contract?"],
    rubric: [
      { criterion: "Context selection", description: "Includes outcome, boundaries, entrypoint, contract, search permission, and validation." },
      { criterion: "Token discipline", description: "Explains omissions and uses progressive context expansion rather than bulk pasting." },
    ],
    sourceType: "original",
    sourceUrls: [],
    licenseNote: ORIGINAL_NOTE,
    qualityScore: 5,
  },
  {
    slug: "ai-select-files-for-timeout-fix",
    title: "Choose the Five Files an Agent Needs for a Timeout Bug",
    type: "ai_usage",
    difficulty: "medium",
    topics: ["context-selection", "debugging", "architecture"],
    targetRoles: ["backend_swe", "infrastructure_swe", "platform_engineer"],
    companyStyles: ["big_tech", "startup", "infra_heavy"],
    estimatedMinutes: 25,
    prompt: "A repository has 2,000 files and an outbound request times out in production but not tests. You may initially provide a coding agent only five files or command outputs. Choose the context sequence, justify each item, and explain how evidence from imports, configuration lookup, and call sites changes the next context you provide.",
    constraints: "Do not assume the timeout is in the HTTP client. Include runtime configuration and an existing test or analogue while avoiding secrets and full production logs.",
    hints: ["Start from the failing request's entrypoint and follow data/configuration flow across boundaries.", "A targeted search result can be more useful than a large directory dump."],
    solutionOutline: "Provide the handler/job entrypoint, the outbound client wrapper, timeout configuration schema/defaults, the closest focused test, and a concise call-site/config-key search result. Redact secrets and include only the relevant log trace with timestamps if available. Ask the agent to state observed facts and missing evidence before editing. Expand context based on the discovered dependency path—for example retry middleware or deployment config—rather than selecting files by directory proximity.",
    commonMistakes: ["Supplying five implementation files while omitting configuration and the test contract.", "Dumping an entire production log or environment file and leaking secrets without improving causal evidence."],
    followUpQuestions: ["What changes when the agent has direct repository search and terminal access?", "How do you provide enough observability evidence without anchoring the agent to one hypothesis?"],
    rubric: [
      { criterion: "Dependency tracing", description: "Selects entrypoint, boundary wrapper, configuration, tests, and targeted search evidence." },
      { criterion: "Adaptive workflow", description: "Expands context from observed dependencies while protecting secrets and avoiding anchoring." },
    ],
    sourceType: "original",
    sourceUrls: [],
    licenseNote: ORIGINAL_NOTE,
    qualityScore: 4,
  },
  {
    slug: "ai-hallucinated-sdk-review",
    title: "Catch the SDK Methods That Do Not Exist",
    type: "ai_usage",
    difficulty: "hard",
    topics: ["code-review", "hallucinations", "apis", "verification"],
    targetRoles: ["backend_swe", "platform_engineer", "new_grad_swe"],
    companyStyles: ["startup", "big_tech", "fintech"],
    estimatedMinutes: 30,
    prompt: "An AI-generated integration looks idiomatic but imports a symbol absent from the installed SDK, uses an option introduced in a newer major version, and assumes retries are automatic. Build a review procedure that finds these failures before merge and distinguishes repository evidence, official documentation, and model claims.",
    constraints: "The project is pinned to its current dependency version. Upgrading is outside scope unless explicitly justified, and tests cannot call the real paid service in CI.",
    hints: ["Typechecking catches some invented APIs, but dynamic libraries and semantic assumptions need additional evidence.", "Inspect the installed package and version-matched official reference, then encode the contract in a fake or transport-level test."],
    solutionOutline: "Confirm the lockfile version, inspect exported types/runtime symbols in the installed package, and consult official documentation for that exact version. Run typecheck and a minimal import/runtime test. Verify retry, timeout, pagination, and error semantics rather than inferring them from method names. Build a fake transport or recorded contract fixture that asserts request shape and representative responses without hitting the paid service. Record any assumption that remains external and reject the patch until unsupported APIs are replaced.",
    commonMistakes: ["Trusting polished syntax or the model's citation without checking the pinned installed version.", "Upgrading the SDK solely to make generated code compile, silently expanding scope and migration risk."],
    followUpQuestions: ["When is a mock too coupled to the hallucinated implementation to provide useful evidence?", "How should the review change for a dynamically typed SDK with sparse type information?"],
    rubric: [
      { criterion: "Evidence hierarchy", description: "Checks lockfile, installed exports, versioned official docs, and executable behavior." },
      { criterion: "Contract verification", description: "Tests request and error semantics without requiring the live paid service." },
    ],
    sourceType: "original",
    sourceUrls: [],
    licenseNote: ORIGINAL_NOTE,
    qualityScore: 5,
  },
  {
    slug: "ai-tests-before-acceptance",
    title: "Turn an AI Patch into a Verifiable Change",
    type: "ai_usage",
    difficulty: "medium",
    topics: ["testing", "verification", "code-review", "risk"],
    targetRoles: ["backend_swe", "infrastructure_swe", "mid_level_swe"],
    companyStyles: ["big_tech", "startup", "infra_heavy"],
    estimatedMinutes: 30,
    prompt: "A coding agent fixes a retry loop that previously duplicated writes. The diff is plausible and unit tests still pass, but no test reproduces the incident. Specify the tests and checks required before acceptance, including the failure injection, invariant, concurrency boundary, and production observability you expect.",
    constraints: "Do not accept snapshots as the primary assertion. The test must fail on the old implementation and remain deterministic in CI.",
    hints: ["Start from the incident's externally observable invariant, not the generated control flow.", "Inject the ambiguous failure at the boundary where the write may succeed but the response is lost."],
    solutionOutline: "Write a regression test that injects a lost response after the durable write, retries with the same idempotency key, and asserts exactly one business effect plus a stable returned outcome. Add a concurrent duplicate test using synchronization barriers instead of sleeps, and boundary tests for exhausted retries and non-retryable errors. Run lint, types, focused tests, full tests, and build; inspect the diff for changed contracts. Require metrics/logs for retry attempts, dedupe hits, and terminal failures so production can confirm the invariant.",
    commonMistakes: ["Testing the new helper's internal call count without recreating the ambiguous boundary condition.", "Using timing sleeps for concurrency tests, producing flaky evidence that can pass without exercising the race."],
    followUpQuestions: ["How do mutation testing or temporarily reverting the fix demonstrate that the regression test is meaningful?", "What evidence is sufficient when the failure depends on an external system that cannot run in CI?"],
    rubric: [
      { criterion: "Regression design", description: "Recreates the original ambiguous failure and asserts the external idempotency invariant." },
      { criterion: "Acceptance discipline", description: "Covers deterministic concurrency, command validation, diff review, and observability." },
    ],
    sourceType: "original",
    sourceUrls: [],
    licenseNote: ORIGINAL_NOTE,
    qualityScore: 5,
  },
]);
