import { defineProblems, DOCS_INSPIRED_NOTE } from "./types";

export const starterDatabaseProblems = defineProblems([
  {
    slug: "snapshot-isolation-write-skew-oncall",
    title: "Two Doctors Both Go Off Call",
    type: "databases",
    difficulty: "hard",
    topics: ["transactions", "isolation", "write-skew", "serializability"],
    targetRoles: ["backend_swe", "distributed_systems_engineer", "mid_level_swe"],
    companyStyles: ["big_tech", "fintech", "infra_heavy"],
    estimatedMinutes: 35,
    prompt: "Two concurrent transactions each read that two doctors are on call, then each updates a different doctor to off call. Under snapshot isolation both commit, violating the invariant that at least one doctor remains. Trace the anomaly and compare serializable isolation, explicit locking, and modeling the invariant as a lockable row.",
    constraints: "The solution must protect a predicate spanning multiple rows. Explain why row-level locks on only the rows being updated are insufficient.",
    hints: ["The writes do not conflict physically even though the decisions conflict logically.", "Make the predicate participate in conflict detection through serializable isolation or a shared guard row."],
    solutionOutline: "Each transaction reads the same snapshot and updates a disjoint row, so snapshot isolation sees no write-write conflict and permits write skew. Serializable isolation can abort one transaction when it detects the dangerous dependency; callers must retry. Alternatively lock all rows contributing to the invariant in a stable order, or maintain an on-call group/guard row that every transition locks and validates. A plain count check plus updating only self is not safe. Add a two-session concurrency test and monitor serialization retries.",
    commonMistakes: ["Calling the anomaly a lost update even though neither transaction overwrites the other's row.", "Using SELECT FOR UPDATE only on the doctor being removed, leaving the shared predicate unlocked."],
    followUpQuestions: ["How does PostgreSQL serializable snapshot isolation detect dangerous structures?", "Can a deferred constraint encode this multi-row invariant directly?"],
    rubric: [
      { criterion: "Anomaly trace", description: "Shows both snapshots, disjoint writes, successful commits, and the broken predicate." },
      { criterion: "Isolation remedy", description: "Offers serializable retry or complete locking/modeling of the shared invariant." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://www.postgresql.org/docs/current/transaction-iso.html"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 5,
  },
  {
    slug: "account-transfer-deadlock-order",
    title: "Transfers That Deadlock in Opposite Directions",
    type: "databases",
    difficulty: "medium",
    topics: ["deadlocks", "transactions", "locking", "retries"],
    targetRoles: ["backend_swe", "quant_developer", "mid_level_swe"],
    companyStyles: ["fintech", "big_tech", "startup"],
    estimatedMinutes: 30,
    prompt: "Transfer A locks account 10 then account 20, while a concurrent reverse transfer locks 20 then 10. Production reports periodic deadlock victims even though every statement is fast. Draw the wait-for cycle, repair lock acquisition order, and define retry and idempotency behavior for the aborted transaction.",
    constraints: "Balances must update atomically. Retries can occur after the caller loses the response, so a transfer ID must prevent applying money movement twice.",
    hints: ["A deterministic global order removes this two-resource lock cycle.", "Deadlock retry and request replay are separate problems; both need explicit handling."],
    solutionOutline: "The transactions each hold one row and wait for the other, creating a cycle the database resolves by aborting a victim. Lock both account rows in ascending account ID order regardless of transfer direction, then validate and update. Keep transactions short and retry deadlock/serialization errors with bounded jitter. Persist a unique transfer_id and resulting status in the same transaction so caller retries return the original result instead of moving funds again.",
    commonMistakes: ["Increasing lock timeout, which extends the stall without breaking the wait-for cycle.", "Retrying the transaction without an idempotency key for ambiguous client or network retries."],
    followUpQuestions: ["How do multi-account journal entries generalize deterministic lock ordering?", "Why can query-plan changes reintroduce deadlocks even when application code appears ordered?"],
    rubric: [
      { criterion: "Deadlock mechanics", description: "Draws the held and requested locks and identifies the exact wait-for cycle." },
      { criterion: "Operational fix", description: "Combines global ordering, short transactions, bounded retries, and durable idempotency." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://www.postgresql.org/docs/current/explicit-locking.html#LOCKING-DEADLOCKS"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 5,
  },
  {
    slug: "webhook-idempotency-transaction-boundary",
    title: "The Webhook That Creates Duplicate Subscriptions",
    type: "databases",
    difficulty: "medium",
    topics: ["idempotency", "unique-constraints", "transactions", "webhooks"],
    targetRoles: ["backend_swe", "platform_engineer", "mid_level_swe"],
    companyStyles: ["startup", "fintech", "big_tech"],
    estimatedMinutes: 30,
    prompt: "A payment provider retries the same webhook concurrently. The handler checks an events table, creates a subscription, then inserts the event ID. Two requests can both pass the check and create duplicate subscriptions. Redesign the transaction so the database arbitrates uniqueness and retries return the existing outcome.",
    constraints: "Delivery is at least once, concurrent duplicates are possible, and process crashes can happen between statements. Do not depend on an in-memory cache or read-then-write check.",
    hints: ["A unique constraint is the serialization point; an application pre-check is not.", "The dedupe record and business mutation must commit or roll back together."],
    solutionOutline: "Create a unique constraint on provider plus event_id. Begin a transaction and attempt the event insert first using INSERT ... ON CONFLICT semantics. Only the transaction that creates the claim performs the subscription mutation and stores a stable outcome; duplicates read that outcome after the winner commits. Keep all database effects in one transaction. If an external side effect is required, write an outbox record in the transaction and deliver it idempotently later. Retain dedupe records for at least the provider's replay horizon.",
    commonMistakes: ["Keeping the SELECT-before-INSERT check and assuming a transaction alone makes it atomic.", "Committing the dedupe marker before the business mutation, which can turn a crash into a permanently dropped event."],
    followUpQuestions: ["How should a duplicate request behave while the winning transaction is still in progress?", "What retention and partitioning strategy keeps a large webhook inbox manageable?"],
    rubric: [
      { criterion: "Race elimination", description: "Uses a unique database write as the concurrency arbiter rather than a pre-check." },
      { criterion: "Atomic outcome", description: "Keeps claim, business state, and durable result together and handles external effects." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-UNIQUE-CONSTRAINTS", "https://www.postgresql.org/docs/current/sql-insert.html"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 5,
  },
  {
    slug: "long-snapshot-vacuum-bloat",
    title: "The Analytics Transaction Blocking Cleanup",
    type: "databases",
    difficulty: "hard",
    topics: ["mvcc", "vacuum", "transactions", "observability"],
    targetRoles: ["backend_swe", "infrastructure_swe", "platform_engineer"],
    companyStyles: ["big_tech", "infra_heavy", "fintech"],
    estimatedMinutes: 35,
    prompt: "A dashboard opens a repeatable-read transaction and remains idle for hours while users inspect results. The primary database accumulates dead tuples, table size grows, and autovacuum runs without reclaiming space. Explain the MVCC horizon held by the old snapshot, prove the cause using database views, and redesign the read workflow.",
    constraints: "The dashboard needs internally consistent results, but it does not need to hold locks or a live transaction while the user reads the page.",
    hints: ["Vacuum cannot remove row versions that remain visible to any active snapshot.", "Consistency can be materialized into a short-lived result rather than represented by an hours-long transaction."],
    solutionOutline: "The long repeatable-read snapshot keeps an old xmin horizon, so vacuum must retain dead versions that snapshot could still see. Correlate pg_stat_activity transaction age/state with pg_stat_user_tables dead tuples and vacuum progress. End the transaction immediately after computing results; materialize the report, use a replica/export job, or paginate from a captured boundary where appropriate. Add idle_in_transaction_session_timeout and transaction-age alerts as guardrails, then vacuum/analyze and assess whether bloat requires online table/index maintenance.",
    commonMistakes: ["Blaming autovacuum tuning alone when an active snapshot legally prevents tuple removal.", "Killing the session and expecting filesystem size to shrink immediately without understanding reuse versus rewrite."],
    followUpQuestions: ["How do logical replication slots create a related retention horizon?", "When would a read replica isolate workload but still fail to solve snapshot retention on that replica?"],
    rubric: [
      { criterion: "MVCC explanation", description: "Connects the old snapshot horizon to retained dead tuples and table growth." },
      { criterion: "Evidence and redesign", description: "Names relevant observability, shortens transaction lifetime, and adds guardrails." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://www.postgresql.org/docs/current/routine-vacuuming.html", "https://www.postgresql.org/docs/current/monitoring-stats.html"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 5,
  },
]);
