import { defineProblems, DOCS_INSPIRED_NOTE } from "./types";

export const starterOptimizationProblems = defineProblems([
  {
    slug: "catastrophic-regex-routing-rule",
    title: "The Validation Regex That Pins a Core",
    type: "optimization",
    difficulty: "hard",
    topics: ["regex", "complexity", "security", "profiling"],
    targetRoles: ["backend_swe", "infrastructure_swe", "platform_engineer"],
    companyStyles: ["startup", "big_tech", "infra_heavy"],
    estimatedMinutes: 35,
    prompt: "A route-rule validator uses a backtracking regex with nested repetition. Valid inputs return instantly, but a 40-character near-match consumes seconds of CPU and can be sent before authentication. Explain the backtracking explosion, produce a linear-time parser or safe pattern, and design a benchmark that prevents regression.",
    constraints: "Treat input as hostile and bounded only by the HTTP request limit. The repair must reject the same invalid grammar without relying solely on a shorter maximum length.",
    hints: ["Near-matches force the engine to explore many partitions created by overlapping nested quantifiers.", "A small scanner or a non-backtracking engine gives a complexity guarantee that pattern tweaks may not."],
    solutionOutline: "Profile samples in the regex engine and demonstrate runtime growing exponentially on strings that match the repeated prefix but fail at the suffix. Replace the validator with a single-pass state machine for segments and separators, or use an RE2-style engine with linear-time guarantees. If retaining the current engine, remove ambiguous nested quantifiers and add strict length limits as defense in depth. Benchmark adversarial lengths and assert a runtime slope or deadline, not one happy-path duration.",
    commonMistakes: ["Optimizing the valid case while ignoring near-match input where catastrophic backtracking occurs.", "Calling a length cap the complete fix even though allowed lengths can still exhaust worker capacity."],
    followUpQuestions: ["What expressiveness does a linear-time regex engine usually give up?", "How would you set a request-level CPU or wall-clock budget around validation?"],
    rubric: [
      { criterion: "Complexity explanation", description: "Connects ambiguous repetition and suffix failure to exponential backtracking paths." },
      { criterion: "Durable mitigation", description: "Selects a linear-time design and tests adversarial growth with defense in depth." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://github.com/google/re2/wiki/Syntax"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 5,
  },
  {
    slug: "deep-offset-audit-pagination",
    title: "Page 8,000 Gets Slower Every Day",
    type: "optimization",
    difficulty: "medium",
    topics: ["sql", "pagination", "indexes", "query-plans"],
    targetRoles: ["backend_swe", "platform_engineer", "mid_level_swe"],
    companyStyles: ["fintech", "big_tech", "startup"],
    estimatedMinutes: 30,
    prompt: "An audit-log endpoint orders by created_at DESC, id DESC and uses LIMIT 100 OFFSET n. Early pages are fast, but exports traversing millions of rows slow progressively and show duplicate or skipped entries during concurrent inserts. Explain both the plan cost and consistency problem, then replace offset traversal with indexed keyset pagination.",
    constraints: "Ordering must be deterministic when timestamps collide. The cursor must identify a strict position and the query must use a matching composite index.",
    hints: ["OFFSET still requires finding and discarding preceding rows.", "The next predicate is lexicographic on (created_at, id), matching both ORDER BY directions."],
    solutionOutline: "Deep offset scans or walks all preceding index entries before returning 100, so total export cost becomes quadratic across pages. Concurrent inserts shift ordinal positions. Use cursor values from the last row and query WHERE (created_at, id) < (?, ?) ORDER BY created_at DESC, id DESC LIMIT 100 with an index on (created_at DESC, id DESC). Encode and validate cursors opaquely. Keyset traversal stabilizes relative to the boundary but is not a full snapshot; use a transaction or captured high-water mark when export consistency requires one.",
    commonMistakes: ["Using created_at alone, which loses deterministic ordering and can skip timestamp ties.", "Claiming keyset pagination creates a transactionally consistent export without a snapshot or high-water boundary."],
    followUpQuestions: ["How do backward navigation and mixed sort directions change predicates and indexes?", "What snapshot strategy works when the export takes longer than a safe database transaction?"],
    rubric: [
      { criterion: "Plan literacy", description: "Explains discarded index entries and cumulative deep-offset cost quantitatively." },
      { criterion: "Keyset correctness", description: "Uses a strict composite cursor, matching index, and honest consistency semantics." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://www.postgresql.org/docs/current/queries-limit.html"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 5,
  },
  {
    slug: "fanout-payload-copy-amplification",
    title: "One Market Update, Ten Thousand Copies",
    type: "optimization",
    difficulty: "hard",
    topics: ["memory", "fanout", "serialization", "zero-copy"],
    targetRoles: ["infrastructure_swe", "quant_developer", "backend_swe"],
    companyStyles: ["hft", "big_tech", "infra_heavy"],
    estimatedMinutes: 35,
    prompt: "A feed gateway decodes one update, clones a mutable message per subscriber, serializes each clone, and enqueues separate byte buffers. At 10,000 subscribers, allocation and memory bandwidth dominate while payload bytes are identical for most clients. Redesign the pipeline to share immutable encoded data while preserving per-subscriber filtering and slow-consumer isolation.",
    constraints: "Subscribers cannot mutate shared payloads. Some subscribers require a small personalized header, and one slow client must not retain unbounded historical buffers.",
    hints: ["Separate common immutable body bytes from small per-subscriber metadata.", "Reference counting removes copies but does not itself bound retention by slow consumers."],
    solutionOutline: "Measure allocations and bytes copied per source message, then encode the common body once into an immutable reference-counted buffer. Queue lightweight references plus personalized header metadata, using vectored I/O or a small prefix buffer. Keep subscriber filtering before enqueue. Enforce per-subscriber byte/count limits and disconnect, drop, or conflate according to product semantics so one client cannot pin all shared buffers. Batch system calls only after fixing copy amplification and verify lifetime ownership with stress and race tooling.",
    commonMistakes: ["Proposing a shared mutable object, introducing races and subscriber-specific corruption.", "Using reference counting without queue bounds, allowing a slow subscriber to retain the entire stream."],
    followUpQuestions: ["When is copy-on-write preferable to a strictly immutable encoded representation?", "How would NUMA placement alter the design for multiple network-interface queues?"],
    rubric: [
      { criterion: "Cost decomposition", description: "Separates decode, clone, encode, allocation, copy, and syscall costs using measurements." },
      { criterion: "Ownership and pressure", description: "Shares immutable bytes while bounding retention and isolating slow subscribers." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://man7.org/linux/man-pages/man2/writev.2.html"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 5,
  },
  {
    slug: "batcher-throughput-latency-trap",
    title: "The Batcher That Improves Throughput and Breaks p99",
    type: "optimization",
    difficulty: "medium",
    topics: ["batching", "latency", "backpressure", "capacity-planning"],
    targetRoles: ["backend_swe", "infrastructure_swe", "quant_developer"],
    companyStyles: ["fintech", "hft", "infra_heavy"],
    estimatedMinutes: 30,
    prompt: "A service changes from sending writes immediately to flushing batches only when 1,000 items accumulate. Peak throughput rises, but at low traffic requests wait seconds and p99 violates a 100 ms SLO. Design a dual-trigger batcher, quantify its queueing bounds, and state how overload backpressure should work.",
    constraints: "The downstream supports at most 1,000 items per call. The process has a finite memory budget, and cancellation must not silently discard accepted items.",
    hints: ["Batch size optimizes throughput; a time trigger bounds waiting when arrival rate is low.", "A bounded queue needs an explicit full policy rather than an unbounded promise of future work."],
    solutionOutline: "Flush when either max_batch is reached or max_wait since the first queued item expires. With a 50 ms max wait, batching contributes at most roughly 50 ms before downstream service time and scheduler jitter. Use one owner loop for queue and timer state, reset timers correctly after every flush, and cap total queued items/bytes. On saturation block within caller deadlines, reject with a retryable response, or shed by documented priority; never grow without bound. Instrument batch-size distribution, queue age, flush reason, and rejection rate to tune from real traffic.",
    commonMistakes: ["Adding a periodic timer whose phase can make a newly queued item wait nearly two intervals.", "Bounding the batch but not the queue, leaving memory and accepted-work semantics undefined."],
    followUpQuestions: ["How would adaptive batching react to changing downstream latency?", "What delivery guarantees are required during process shutdown, and how do they affect drain behavior?"],
    rubric: [
      { criterion: "Latency model", description: "Derives a clear queueing bound from a first-item timer and downstream service time." },
      { criterion: "Overload behavior", description: "Defines queue limits, caller-facing backpressure, shutdown, and operational metrics." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://sre.google/sre-book/handling-overload/"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 4,
  },
]);
