import { defineProblems, DOCS_INSPIRED_NOTE } from "./types";

export const starterReadCodeProblems = defineProblems([
  {
    slug: "python-list-mutation-skips-orders",
    title: "The Risk Filter That Skips Every Other Order",
    type: "read_code",
    difficulty: "medium",
    topics: ["python", "iteration", "mutation", "correctness"],
    targetRoles: ["backend_swe", "quant_developer", "new_grad_swe"],
    companyStyles: ["fintech", "quant_fund", "big_tech"],
    estimatedMinutes: 20,
    language: "python",
    prompt: "Read a risk filter that loops over a list of candidate orders and removes rejected orders from that same list. Given six alternating valid and invalid orders, predict the exact output, explain why some invalid orders survive, and propose a correction that preserves input order without relying on accidental iterator behavior.",
    constraints: "Do not run the code initially. Explain the movement of the list iterator index after each removal. The corrected version should be O(n) and should make ownership of the input list explicit.",
    starterCode: "def accepted(orders):\n    for order in orders:\n        if order.qty <= 0 or order.notional > 1_000_000:\n            orders.remove(order)\n    return orders\n",
    hints: ["Track both the iterator's next numeric index and the element that shifts into the removed slot.", "A filter expression or a write-index compaction pass separates traversal from mutation."],
    solutionOutline: "Removing the current element shifts the next element left while the list iterator still advances its index, so the shifted element is never examined. Walk a concrete list to show the skipped positions. Prefer returning a new list with a comprehension when callers do not require identity preservation. If in-place mutation is required, assign the filtered result to orders[:] or use a stable write-index pass. State whether callers retaining the original list object must observe the change.",
    commonMistakes: ["Saying list.remove is merely slow without explaining the correctness failure caused by index movement.", "Iterating over orders.copy() without discussing O(n) extra memory or whether mutating the caller-owned list is intended."],
    followUpQuestions: ["How would the answer change for a deque or linked list with an erase-capable iterator?", "Can you design a property-based test that exposes skipped adjacent invalid orders?"],
    rubric: [
      { criterion: "Trace accuracy", description: "Predicts the surviving invalid elements and explains iterator-index movement precisely." },
      { criterion: "Repair quality", description: "Chooses an O(n) fix and states whether input identity and mutation are preserved." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://docs.python.org/3/reference/compound_stmts.html#the-for-statement"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 4,
  },
  {
    slug: "go-slice-capacity-aliasing",
    title: "The Go Append That Mutates Another Request",
    type: "read_code",
    difficulty: "hard",
    topics: ["go", "slices", "aliasing", "memory"],
    targetRoles: ["backend_swe", "infrastructure_swe", "mid_level_swe"],
    companyStyles: ["big_tech", "infra_heavy", "startup"],
    estimatedMinutes: 25,
    language: "go",
    prompt: "A service derives two request batches from one backing slice, appends a marker to the first batch, and later observes an element in the second batch changing. Read the code, predict results for spare-capacity and full-capacity inputs, and explain why the behavior changes when append reallocates.",
    constraints: "Reason in terms of slice pointer, length, and capacity. The fix must prevent mutation leaks across independently owned batches without assuming append always allocates.",
    starterCode: "func split(ids []string) ([]string, []string) {\n    left := ids[:2]\n    right := ids[2:]\n    left = append(left, \"audit\")\n    return left, right\n}\n",
    hints: ["A slice is a descriptor over a backing array; reslicing does not copy elements.", "Use a full slice expression to cap capacity, or make an explicit copy when ownership must be independent."],
    solutionOutline: "When ids has capacity beyond len(left), append writes into the shared backing array at index two, replacing right[0]. When left has no spare capacity, append allocates and right is unchanged. This capacity-dependent behavior makes the bug intermittent across callers. Use left := ids[:2:2] to force append allocation, or copy each independently owned result with append([]string(nil), ...). Prefer explicit copying at ownership boundaries and test both capacity cases.",
    commonMistakes: ["Treating slices as value-owned arrays because the slice descriptor itself is passed by value.", "Fixing only this append while leaving returned slices sharing mutable storage with the caller."],
    followUpQuestions: ["How can a three-index slice expression document and enforce an append boundary?", "What race can occur if two goroutines mutate disjoint-looking slices that overlap the same array?"],
    rubric: [
      { criterion: "Memory model", description: "Explains pointer, length, capacity, and the allocation-dependent append behavior." },
      { criterion: "Ownership fix", description: "Uses capacity limiting or copying intentionally and identifies remaining aliases." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://go.dev/blog/slices-intro"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 5,
  },
  {
    slug: "java-treeset-comparator-collision",
    title: "The TreeSet That Drops Distinct Trades",
    type: "read_code",
    difficulty: "medium",
    topics: ["java", "comparator", "collections", "equality"],
    targetRoles: ["backend_swe", "quant_developer", "mid_level_swe"],
    companyStyles: ["fintech", "big_tech", "quant_fund"],
    estimatedMinutes: 25,
    language: "java",
    prompt: "A TreeSet stores trades using a comparator that compares timestamp only. Multiple trades can share a timestamp but have different IDs. Predict the set size and contains behavior, explain why no equals or hashCode method can repair this comparator, and redesign ordering so iteration remains deterministic without dropping trades.",
    constraints: "The collection must retain every distinct trade ID and iterate by timestamp, then ID. Discuss what compare(a,b) == 0 means to a sorted set.",
    starterCode: "Comparator<Trade> byTime = Comparator.comparingLong(Trade::timestampNanos);\nSet<Trade> trades = new TreeSet<>(byTime);\ntrades.add(new Trade(100, \"A\"));\ntrades.add(new Trade(100, \"B\"));\n",
    hints: ["TreeSet uses comparator equivalence, not hash buckets, to decide whether an element already exists.", "A total order can compare timestamp first and a stable unique identifier second."],
    solutionOutline: "The comparator returns zero for A and B, so TreeSet treats them as the same set element and the second add returns false. contains for another trade at timestamp 100 can return true even when its ID differs. equals and hashCode are irrelevant to this tree navigation. Compose comparingLong(timestamp).thenComparing(id), and ensure the tie-break fields are immutable while stored. If uniqueness is ID-only but presentation is time-ordered, use a Map by ID plus a separate ordered index.",
    commonMistakes: ["Changing hashCode even though TreeSet never uses it to establish comparator equivalence.", "Adding a mutable field as a tie-breaker, then modifying it while the element remains in the tree."],
    followUpQuestions: ["When is a comparator inconsistent with equals acceptable, and what surprises remain?", "How would you support duplicate timestamps and duplicate external IDs from different venues?"],
    rubric: [
      { criterion: "Collection semantics", description: "Connects comparator zero directly to sorted-set identity and predicts API behavior." },
      { criterion: "Ordering design", description: "Builds a stable total order and considers immutability and alternate indexes." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/TreeSet.html"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 5,
  },
  {
    slug: "javascript-microtask-ordering-response",
    title: "The Response That Logs Before Its Work Finishes",
    type: "read_code",
    difficulty: "medium",
    topics: ["javascript", "promises", "event-loop", "async"],
    targetRoles: ["fullstack_swe", "backend_swe", "new_grad_swe"],
    companyStyles: ["startup", "big_tech", "fintech"],
    estimatedMinutes: 20,
    language: "javascript",
    prompt: "Read an HTTP handler that starts asynchronous enrichment inside Array.forEach, immediately serializes the records, and logs from both promise continuations and a zero-delay timer. Predict the observable ordering and returned payload, then rewrite it with explicit concurrency and failure semantics.",
    constraints: "Explain why forEach does not await an async callback. The corrected version must state whether one enrichment failure rejects the whole request or produces a partial response.",
    starterCode: "async function handler(records) {\n  records.forEach(async (r) => { r.score = await score(r); console.log('scored'); });\n  setTimeout(() => console.log('timer'), 0);\n  console.log('returning');\n  return JSON.stringify(records);\n}\n",
    hints: ["forEach ignores callback return values, including promises.", "Map to promises and await Promise.all when bounded fan-out and fail-fast behavior are acceptable."],
    solutionOutline: "The handler schedules enrichment promises, logs returning, and resolves with records before scoring completes. Promise continuation versus timer order depends on when score settles, so avoid claiming one universal trace without the score implementation. Replace forEach with await Promise.all(records.map(async ...)) for concurrent fail-fast work, or a for...of loop for sequential work. For partial results, use Promise.allSettled and explicitly represent per-record failures. Add a concurrency limiter when record count is unbounded.",
    commonMistakes: ["Claiming async forEach waits because the surrounding function is async.", "Using Promise.all for unbounded input without discussing downstream concurrency or failure behavior."],
    followUpQuestions: ["How would you cap scoring at eight concurrent calls while retaining result order?", "What changes if score sometimes throws synchronously before returning a promise?"],
    rubric: [
      { criterion: "Execution trace", description: "Separates synchronous execution, promise settlement, and timer scheduling without overclaiming." },
      { criterion: "Concurrency contract", description: "Provides a correct rewrite and states ordering, failure, and concurrency semantics." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach", "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 4,
  },
]);
