import { defineProblems, DOCS_INSPIRED_NOTE, EDU_INSPIRED_NOTE } from "./types";

export const starterQuantDevProblems = defineProblems([
  {
    slug: "python-hash-randomized-sharding",
    title: "The Python Shard Map That Changes After Restart",
    type: "quant_dev",
    difficulty: "medium",
    topics: ["python", "hashing", "determinism", "distributed-systems"],
    targetRoles: ["quant_developer", "hft_swe", "backend_swe"],
    companyStyles: ["quant_fund", "hft", "fintech"],
    estimatedMinutes: 25,
    language: "python",
    prompt: "A market-data recorder assigns symbols to files with hash(symbol) % 32. After each process restart, many symbols move to different files, breaking replay expectations and cache locality. Explain Python hash randomization, distinguish equality/hash correctness from cross-process stability, and choose a stable partition function with a migration plan.",
    constraints: "Assignments must match across hosts and language implementations. The function must define byte encoding, algorithm version, and shard-count behavior.",
    hints: ["Python intentionally salts hashes for selected built-in types between interpreter processes.", "Use a documented stable digest or non-cryptographic hash over canonical bytes, then version the mapping."],
    solutionOutline: "Python's str hash is process-salted, so it satisfies in-process dictionary requirements but is not a persistent identifier. Canonically encode symbols, apply a specified stable algorithm such as SHA-256 with a chosen byte-to-integer convention, and map to shards. Persist a hash_version and shard_count because modulo remaps most keys when the count changes; consistent hashing or rendezvous hashing reduces movement. Run old and new mappings in parallel during migration and verify replay routing.",
    commonMistakes: ["Setting PYTHONHASHSEED globally as the permanent distributed protocol, coupling correctness to runtime configuration.", "Choosing a stable algorithm but omitting encoding, byte order, versioning, or shard-count migration."],
    followUpQuestions: ["Why is a cryptographic digest often acceptable here even if a faster hash exists?", "Compare modulo, consistent hashing, and rendezvous hashing under shard additions."],
    rubric: [
      { criterion: "Runtime knowledge", description: "Separates Python hash-table correctness from deterministic cross-process partitioning." },
      { criterion: "Protocol design", description: "Specifies canonical bytes, algorithm version, mapping, and a safe remapping strategy." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://docs.python.org/3/reference/datamodel.html#object.__hash__", "https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 5,
  },
  {
    slug: "cpp-moved-handle-double-close",
    title: "The Moved Socket That Closes Twice",
    type: "quant_dev",
    difficulty: "hard",
    topics: ["cpp", "move-semantics", "raii", "resource-ownership"],
    targetRoles: ["quant_developer", "hft_swe", "infrastructure_swe"],
    companyStyles: ["hft", "quant_fund", "infra_heavy"],
    estimatedMinutes: 35,
    language: "cpp",
    prompt: "A custom Socket RAII wrapper uses compiler-generated move operations for an integer file descriptor. Moving it copies the descriptor, so both destructors call close; occasionally the second close targets a newly reused descriptor. Implement correct Rule-of-Five behavior, define the moved-from invariant, and discuss noexcept and container relocation.",
    constraints: "Copying must be disabled unless it duplicates the operating-system handle intentionally. Destruction and move assignment must never leak or double-close resources.",
    hints: ["Moving an integer is still a copy; ownership transfer requires invalidating the source.", "Move assignment must release the destination's current resource before taking the source resource."],
    solutionOutline: "Delete copy construction and assignment. Store an invalid sentinel, close only valid handles, and implement a noexcept move constructor with std::exchange(other.fd_, invalid). Move assignment checks self-assignment, closes the current handle, then exchanges from the source. A small unique-handle base can centralize this invariant. noexcept lets standard containers prefer moves during reallocation. Explain why a delayed double-close can corrupt unrelated connections after descriptor reuse, making this more dangerous than a harmless EBADF.",
    commonMistakes: ["Using std::move on the integer and assuming ownership moved automatically.", "Overwriting the destination during move assignment without first releasing its existing descriptor."],
    followUpQuestions: ["When should copying call dup, and why might an explicit clone method be clearer?", "How would you generalize the wrapper for Windows handles or custom deleters?"],
    rubric: [
      { criterion: "Ownership invariant", description: "Defines exactly one valid owner and an inert, safely destructible moved-from state." },
      { criterion: "Implementation detail", description: "Covers copy deletion, both move operations, release order, self-move, and noexcept." },
    ],
    sourceType: "educational_inspired",
    sourceUrls: ["https://en.cppreference.com/w/cpp/language/rule_of_three.html", "https://en.cppreference.com/w/cpp/utility/exchange.html"],
    licenseNote: EDU_INSPIRED_NOTE,
    qualityScore: 5,
  },
  {
    slug: "multicast-gap-recovery-design",
    title: "Recovering a Gap in a Multicast Market Feed",
    type: "quant_dev",
    difficulty: "hard",
    topics: ["udp", "tcp", "market-data", "sequence-numbers"],
    targetRoles: ["quant_developer", "hft_swe", "infrastructure_swe"],
    companyStyles: ["hft", "quant_fund", "fintech"],
    estimatedMinutes: 40,
    prompt: "A venue distributes incremental book updates over UDP multicast and offers snapshot plus replay recovery over a separate channel. Your handler receives sequence 4102 after 4100. Design the state machine from gap detection through a trustworthy live book, and explain why switching the whole feed to TCP is not automatically better.",
    constraints: "Packets may be lost, duplicated, reordered, or arrive while recovery is in progress. Trading decisions must never use a silently incomplete book.",
    hints: ["Sequence numbers turn loss into a detectable state transition; they do not repair state by themselves.", "Buffer live incrementals while obtaining a snapshot/replay boundary, then apply only a contiguous sequence."],
    solutionOutline: "Track expected sequence per channel. On a forward gap, mark the book stale immediately, stop publishing it to strategies, buffer bounded live packets, and request replay or a snapshot. Establish a recovery baseline sequence, discard duplicates below it, then apply buffered/replayed updates only in contiguous order until caught up. Time out or restart recovery if bounds are exceeded. UDP multicast offers one-to-many delivery without sender head-of-line blocking; TCP provides ordered reliable streams but a lost segment stalls later bytes and per-client fanout costs differ. The system uses both according to latency and recovery roles.",
    commonMistakes: ["Continuing to trade from the partially updated book while recovery runs in the background.", "Equating UDP with undetectable loss even though application sequence numbers explicitly expose gaps."],
    followUpQuestions: ["How do redundant A/B multicast feeds reduce recovery frequency without double-applying messages?", "What metrics distinguish network loss, handler overload, and packet drops in the kernel receive queue?"],
    rubric: [
      { criterion: "Recovery state machine", description: "Covers stale marking, buffering, baseline acquisition, deduplication, and contiguous catch-up." },
      { criterion: "Transport reasoning", description: "Explains multicast fanout, TCP head-of-line behavior, and the complementary recovery channel." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://www.rfc-editor.org/rfc/rfc768", "https://www.rfc-editor.org/rfc/rfc9293"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 5,
  },
  {
    slug: "order-book-sequence-state-machine",
    title: "Building a Correct Incremental Order Book",
    type: "quant_dev",
    difficulty: "hard",
    topics: ["order-books", "state-machines", "market-data", "correctness"],
    targetRoles: ["quant_developer", "hft_swe"],
    companyStyles: ["hft", "quant_fund", "fintech"],
    estimatedMinutes: 40,
    prompt: "Implement the reasoning for an L2 order-book consumer receiving snapshot, insert/update, delete, duplicate, and reset messages with monotonically increasing sequence numbers. Define invariants, handling for unknown deletes and crossed books, and the conditions under which downstream strategies may consume the state.",
    constraints: "Messages can duplicate or gap. Price and quantity use fixed-point integers. A reset invalidates all prior levels, and recovery must not publish intermediate state.",
    hints: ["Correctness starts with explicit states such as empty, recovering, live, and stale.", "Unknown deletes can indicate a missed update, a protocol rule, or an implementation bug; the feed specification decides which."],
    solutionOutline: "Model EMPTY, RECOVERING, LIVE, and STALE states. Build snapshots off to the side, validate their sequence and invariants, then atomically publish. In LIVE, ignore documented duplicates, require the next sequence, and transition to STALE on gaps or invalid protocol events. Apply fixed-point updates, delete zero quantity, and verify best bid is below best ask unless the venue permits locked/crossed states. Reset clears state and requires a fresh baseline. Only publish immutable snapshots or versioned views while LIVE, with counters for gaps, unknown deletes, crosses, and recovery duration.",
    commonMistakes: ["Applying post-gap updates to the last known book and treating the result as approximately correct.", "Using floating-point prices as map keys, creating equality and ordering errors."],
    followUpQuestions: ["How does an L3 book change data structures and cancel/replace handling?", "How would one writer publish consistent lock-free snapshots to many strategy threads?"],
    rubric: [
      { criterion: "State and invariants", description: "Defines explicit lifecycle states, sequence rules, fixed-point storage, and book validation." },
      { criterion: "Publication safety", description: "Prevents incomplete state from reaching consumers and supplies recovery observability." },
    ],
    sourceType: "original",
    sourceUrls: [],
    licenseNote: "Original Interview OS scenario based on public market-data protocol concepts; no proprietary feed specification or problem text is used.",
    qualityScore: 5,
  },
]);
