import { defineProblems, ORIGINAL_NOTE } from "./types";
import { learningModuleId, learningPathId, lessonId } from "../../src/lib/learning";

const DSA_PATH = learningPathId("dsa-confidence-builder");
const BACKEND_PATH = learningPathId("backend-swe");
const SYSTEM_PATH = learningPathId("system-design");
const AI_PATH = learningPathId("ai-efficient-engineer");
const DSA_ARRAYS = learningModuleId("dsa-confidence-builder", "arrays-hashmaps-two-pointers");
const DSA_WINDOW = learningModuleId("dsa-confidence-builder", "sliding-window-prefix-sums");
const DSA_STACKS = learningModuleId("dsa-confidence-builder", "stacks-queues-heaps");
const DSA_GRAPHS = learningModuleId("dsa-confidence-builder", "trees-graphs");
const BACKEND_HTTP = learningModuleId("backend-swe", "http-apis-request-flow");
const BACKEND_DB = learningModuleId("backend-swe", "databases-indexes");
const BACKEND_DEBUG = learningModuleId("backend-swe", "observability-debugging");
const AI_PROMPTING = learningModuleId("ai-efficient-engineer", "token-efficient-prompting");
const AI_REVIEW = learningModuleId("ai-efficient-engineer", "reviewing-ai-code");

const LANGUAGES = ["python", "javascript", "typescript"] as const;

export const confidenceWarmupProblems = defineProblems([
  {
    slug: "pair-sum-request-ids",
    title: "Pair of Request Sizes Reaching a Target",
    type: "dsa",
    difficulty: "easy",
    topics: ["arrays", "hash-map", "two-sum"],
    targetRoles: ["new_grad_swe", "backend_swe", "quant_developer"],
    companyStyles: ["big_tech", "startup"],
    estimatedMinutes: 15,
    language: "python",
    functionName: "find_pair",
    testHarnessType: "function_call",
    supportedLanguages: [...LANGUAGES],
    pathIds: [DSA_PATH],
    moduleIds: [DSA_ARRAYS],
    lessonIds: [lessonId(DSA_ARRAYS, "two-sum-hashmap-pattern")],
    confidenceLevel: "warmup",
    prompt: "Given request payload sizes and a target combined size, return the indices of the first pair discovered during a left-to-right scan whose values sum to the target. Return an empty list when no pair exists. Each index may be used once.",
    constraints: "Aim for O(n) time with one pass and O(n) extra space. Check for the complement before storing the current index so an element cannot match itself.",
    starterCode: "def find_pair(values: list[int], target: int) -> list[int]:\n    ...\n",
    tests: [
      { name: "basic pair", input: "[2,7,11,15], 9", expected: "[0,1]", args: [[2, 7, 11, 15], 9], expectedValue: [0, 1] },
      { name: "duplicate values", input: "[3,3], 6", expected: "[0,1]", args: [[3, 3], 6], expectedValue: [0, 1] },
      { name: "no pair", input: "[1,2,3], 20", expected: "[]", args: [[1, 2, 3], 20], expectedValue: [], hidden: true },
    ],
    hints: ["For each value, compute target minus value and ask whether that complement has already appeared."],
    solutionOutline: "Maintain a map from value to its earliest index. At index i, check whether target-values[i] is in the map; if so return the stored index and i. Otherwise store the current value if absent. This is O(n) expected time and handles duplicate values because lookup happens before insertion.",
    commonMistakes: ["Using nested loops after the prompt asks for linear expected time.", "Inserting first and accidentally matching the current element with itself."],
    followUpQuestions: ["How does the solution change when input is sorted?", "How would you return every distinct pair of values?"],
    rubric: [
      { criterion: "Pattern recognition", description: "Uses a complement hashmap and states the one-pass invariant." },
      { criterion: "Boundary handling", description: "Handles duplicates and the no-solution case exactly." },
    ],
    sourceType: "original",
    sourceUrls: [],
    licenseNote: ORIGINAL_NOTE,
    qualityScore: 4,
  },
  {
    slug: "longest-unique-session-streak",
    title: "Longest Streak Without a Repeated Session Type",
    type: "dsa",
    difficulty: "easy",
    topics: ["sliding-window", "strings", "hash-map"],
    targetRoles: ["new_grad_swe", "backend_swe", "fullstack_swe"],
    companyStyles: ["big_tech", "startup"],
    estimatedMinutes: 18,
    language: "python",
    functionName: "longest_unique_streak",
    testHarnessType: "function_call",
    supportedLanguages: [...LANGUAGES],
    pathIds: [DSA_PATH],
    moduleIds: [DSA_WINDOW],
    lessonIds: [lessonId(DSA_WINDOW, "sliding-window-when-it-applies")],
    confidenceLevel: "warmup",
    prompt: "A compact string records consecutive session types, one character per event. Return the length of the longest contiguous streak containing no repeated character. An empty event string has a longest streak of zero.",
    constraints: "Target O(n) time. Use a moving left boundary and remember the most recent index for each character.",
    starterCode: "def longest_unique_streak(events: str) -> int:\n    ...\n",
    tests: [
      { name: "all unique", input: "abc", expected: "3", args: ["abc"], expectedValue: 3 },
      { name: "repeat moves left", input: "abba", expected: "2", args: ["abba"], expectedValue: 2 },
      { name: "empty", input: "", expected: "0", args: [""], expectedValue: 0, hidden: true },
    ],
    hints: ["When a repeated character is inside the current window, move left to one position after its previous index."],
    solutionOutline: "Track left, best, and lastSeen. For each right index, set left=max(left,lastSeen[ch]+1) when ch was seen, update lastSeen, and measure right-left+1. The max prevents the window from moving backward.",
    commonMistakes: ["Moving left backward when the prior occurrence is already outside the window.", "Returning the number of distinct characters globally rather than a contiguous streak."],
    followUpQuestions: ["How would you allow at most two occurrences per character?", "What changes for a stream that cannot be stored fully?"],
    rubric: [
      { criterion: "Window invariant", description: "Maintains a window with no duplicate characters and monotonic boundaries." },
      { criterion: "Edge cases", description: "Handles empty, repeated, and fully unique inputs." },
    ],
    sourceType: "original",
    sourceUrls: [],
    licenseNote: ORIGINAL_NOTE,
    qualityScore: 4,
  },
  {
    slug: "balanced-config-brackets",
    title: "Validate Balanced Configuration Brackets",
    type: "dsa",
    difficulty: "easy",
    topics: ["stack", "strings", "parsing"],
    targetRoles: ["new_grad_swe", "backend_swe", "infrastructure_swe"],
    companyStyles: ["big_tech", "startup"],
    estimatedMinutes: 15,
    language: "python",
    functionName: "balanced_brackets",
    testHarnessType: "function_call",
    supportedLanguages: [...LANGUAGES],
    pathIds: [DSA_PATH],
    moduleIds: [DSA_STACKS],
    confidenceLevel: "warmup",
    prompt: "Given a string containing only parentheses, square brackets, and braces, return whether every opening bracket is closed by the correct type in the correct order. The empty string is valid.",
    constraints: "Use O(n) time and O(n) worst-case space. Reject a closing bracket when the stack is empty or its type does not match.",
    starterCode: "def balanced_brackets(text: str) -> bool:\n    ...\n",
    tests: [
      { name: "nested", input: "{[()]}", expected: "True", args: ["{[()]}"] , expectedValue: true },
      { name: "wrong order", input: "([)]", expected: "False", args: ["([)]"], expectedValue: false },
      { name: "left open", input: "((", expected: "False", args: ["(("], expectedValue: false, hidden: true },
    ],
    hints: ["Push opening brackets; each closing bracket must match the top of the stack."],
    solutionOutline: "Use a map from closing to opening brackets. Push openings. For a closing bracket, fail if the stack is empty or the popped opening differs. Return true only when the stack is empty after scanning.",
    commonMistakes: ["Counting bracket totals without respecting nesting order.", "Returning true without checking for unmatched opening brackets left on the stack."],
    followUpQuestions: ["How would you ignore brackets inside quoted strings?", "How would you report the first invalid position?"],
    rubric: [
      { criterion: "Stack use", description: "Uses last-in-first-out matching for nested delimiters." },
      { criterion: "Completeness", description: "Rejects mismatches, early closings, and leftover openings." },
    ],
    sourceType: "original",
    sourceUrls: [],
    licenseNote: ORIGINAL_NOTE,
    qualityScore: 4,
  },
  {
    slug: "reachable-service-count",
    title: "Count Services Reachable from an API Gateway",
    type: "dsa",
    difficulty: "easy",
    topics: ["graphs", "bfs", "sets"],
    targetRoles: ["new_grad_swe", "backend_swe", "infrastructure_swe"],
    companyStyles: ["big_tech", "infra_heavy"],
    estimatedMinutes: 20,
    language: "python",
    functionName: "count_reachable",
    testHarnessType: "function_call",
    supportedLanguages: [...LANGUAGES],
    pathIds: [DSA_PATH],
    moduleIds: [DSA_GRAPHS],
    confidenceLevel: "warmup",
    prompt: "Services are numbered from zero to n-1 and directed call edges are given as pairs [from, to]. Return how many distinct services, including the start service, are reachable from a given start node.",
    constraints: "Cycles and duplicate edges may exist. Use a visited set so each service is processed at most once.",
    starterCode: "def count_reachable(n: int, edges: list[list[int]], start: int) -> int:\n    ...\n",
    tests: [
      { name: "chain", input: "n=4, 0->1->2", expected: "3", args: [4, [[0, 1], [1, 2]], 0], expectedValue: 3 },
      { name: "cycle", input: "0->1->0", expected: "2", args: [3, [[0, 1], [1, 0]], 0], expectedValue: 2 },
      { name: "isolated start", input: "no edges", expected: "1", args: [3, [], 2], expectedValue: 1, hidden: true },
    ],
    hints: ["Build an adjacency list, then run breadth-first or depth-first search from start."],
    solutionOutline: "Build outgoing adjacency lists. Initialize visited with start and process a queue or stack, adding unseen neighbors. Return visited size. Complexity is O(n+e) time and O(n+e) storage including adjacency.",
    commonMistakes: ["Forgetting to count the start service itself.", "Marking nodes only when removed from the queue and enqueuing duplicates repeatedly."],
    followUpQuestions: ["How would you return the actual reachable set?", "What changes if edges arrive as a stream of updates?"],
    rubric: [
      { criterion: "Graph traversal", description: "Builds adjacency and visits every reachable node once." },
      { criterion: "Cycle safety", description: "Uses a visited set correctly for cycles and duplicate edges." },
    ],
    sourceType: "original",
    sourceUrls: [],
    licenseNote: ORIGINAL_NOTE,
    qualityScore: 4,
  },
  {
    slug: "boolean-env-flag-warmup",
    title: "The Feature Flag String That Is Always True",
    type: "debugging",
    difficulty: "easy",
    topics: ["configuration", "python", "type-conversion"],
    targetRoles: ["backend_swe", "new_grad_swe", "platform_engineer"],
    companyStyles: ["startup", "big_tech"],
    estimatedMinutes: 12,
    language: "python",
    pathIds: [BACKEND_PATH],
    moduleIds: [BACKEND_DEBUG],
    confidenceLevel: "warmup",
    prompt: "A deployment sets FEATURE_ENABLED=false, but Python code checks `if os.getenv('FEATURE_ENABLED'):` and enables the feature. Explain the behavior, implement explicit parsing, and name invalid values that should fail configuration loading.",
    constraints: "Configuration should be parsed once at startup. Accept true/false case-insensitively and reject unknown non-empty values.",
    hints: ["Any non-empty Python string is truthy, including the literal string `false`."],
    solutionOutline: "Read the string, normalize case and whitespace, map an explicit allowed set to booleans, and raise for anything else. Store the parsed boolean in typed configuration rather than reparsing in every request.",
    commonMistakes: ["Using bool(raw), which preserves the original bug.", "Silently treating misspellings as false and hiding deployment mistakes."],
    followUpQuestions: ["How would you distinguish missing from explicitly false?", "Where should configuration validation run in a container deployment?"],
    rubric: [{ criterion: "Root cause", description: "Explains non-empty string truthiness exactly." }, { criterion: "Safe parsing", description: "Uses an explicit accepted-value map and rejects malformed configuration." }],
    sourceType: "original", sourceUrls: [], licenseNote: ORIGINAL_NOTE, qualityScore: 4,
  },
  {
    slug: "missing-await-save-warmup",
    title: "The Handler That Returns Before Saving",
    type: "debugging",
    difficulty: "easy",
    topics: ["javascript", "async", "error-handling"],
    targetRoles: ["backend_swe", "fullstack_swe", "new_grad_swe"],
    companyStyles: ["startup", "big_tech"],
    estimatedMinutes: 15,
    language: "javascript",
    pathIds: [BACKEND_PATH], moduleIds: [BACKEND_HTTP], confidenceLevel: "warmup",
    prompt: "An async HTTP handler calls `repository.save(record)` without await and immediately returns 201. Failed writes become unhandled rejections after the success response. Identify the ordering bug and show a corrected error boundary.",
    constraints: "The response must not claim success before persistence completes. Preserve the original error for centralized HTTP error handling.",
    hints: ["Calling an async function starts work and returns a promise; it does not wait for settlement."],
    solutionOutline: "Await repository.save before returning. Let rejection propagate to the framework error handler or catch only to add context and rethrow. Add a test with a rejecting repository promise and assert no 201 response is produced.",
    commonMistakes: ["Adding try/catch without await, so the asynchronous rejection still escapes.", "Catching the error and returning success anyway."],
    followUpQuestions: ["When is intentionally detached work acceptable?", "How would a transactional outbox change the endpoint boundary?"],
    rubric: [{ criterion: "Ordering diagnosis", description: "Connects the missing await to premature success and unhandled rejection." }, { criterion: "Verification", description: "Adds a deterministic rejection test and preserves error propagation." }],
    sourceType: "original", sourceUrls: [], licenseNote: ORIGINAL_NOTE, qualityScore: 4,
  },
  {
    slug: "membership-set-warmup",
    title: "Replace Repeated List Membership with a Set",
    type: "optimization",
    difficulty: "easy",
    topics: ["complexity", "sets", "profiling"],
    targetRoles: ["backend_swe", "new_grad_swe", "quant_developer"],
    companyStyles: ["big_tech", "startup"],
    estimatedMinutes: 15,
    language: "python",
    pathIds: [DSA_PATH, BACKEND_PATH], moduleIds: [DSA_ARRAYS, BACKEND_DEBUG], confidenceLevel: "warmup",
    prompt: "A loop checks each of 100,000 event IDs with `if event.id in blocked_ids`, where blocked_ids is a 50,000-element list. Explain the runtime shape, replace the lookup structure, and state when conversion cost is worthwhile.",
    constraints: "The blocked collection is reused for the whole batch and IDs are hashable. Preserve the original output order.",
    hints: ["List membership is linear; set membership is expected constant time."],
    solutionOutline: "Build blocked=set(blocked_ids) once before the loop, then filter events in original order. Cost changes from O(events×blocked) worst case to O(blocked+events) expected, using O(blocked) extra memory.",
    commonMistakes: ["Constructing the set inside the event loop.", "Claiming sets preserve the event output order—the loop does that, not the set."],
    followUpQuestions: ["What if IDs are unhashable?", "When might a sorted list plus binary search be preferable?"],
    rubric: [{ criterion: "Complexity", description: "Quantifies the old and new time complexity." }, { criterion: "Placement", description: "Builds the lookup set once and preserves output semantics." }],
    sourceType: "original", sourceUrls: [], licenseNote: ORIGINAL_NOTE, qualityScore: 4,
  },
  {
    slug: "client-per-row-warmup",
    title: "Stop Creating an HTTP Client for Every Row",
    type: "optimization",
    difficulty: "easy",
    topics: ["http", "connection-pooling", "latency"],
    targetRoles: ["backend_swe", "infrastructure_swe", "new_grad_swe"],
    companyStyles: ["startup", "infra_heavy"],
    estimatedMinutes: 15,
    pathIds: [BACKEND_PATH], moduleIds: [BACKEND_HTTP], confidenceLevel: "warmup",
    prompt: "A batch job constructs and closes a new HTTP client for every customer row. Profiles show repeated DNS, TCP, and TLS setup. Explain the cost and restructure ownership so connections can be reused safely.",
    constraints: "The client must have explicit timeouts and be closed once at application or job shutdown, not once per request.",
    hints: ["Move long-lived transport ownership outside the per-row loop."],
    solutionOutline: "Create one configured client/session for the batch, reuse its connection pool across requests, and close it after the job. Measure requests per connection, DNS/TLS time, and total latency before and after.",
    commonMistakes: ["Reusing a response body without closing or draining it.", "Sharing a client whose library is not concurrency-safe without checking its contract."],
    followUpQuestions: ["How should pool size relate to concurrency?", "Where do retries and backpressure belong?"],
    rubric: [{ criterion: "Cost model", description: "Names repeated DNS, handshake, and allocation costs." }, { criterion: "Ownership", description: "Scopes one configured client to the job and closes responses correctly." }],
    sourceType: "original", sourceUrls: [], licenseNote: ORIGINAL_NOTE, qualityScore: 4,
  },
  {
    slug: "recent-orders-index-warmup",
    title: "Choose an Index for Recent Customer Orders",
    type: "databases",
    difficulty: "easy",
    topics: ["indexes", "sql", "query-shape"],
    targetRoles: ["backend_swe", "new_grad_swe", "mid_level_swe"],
    companyStyles: ["startup", "big_tech", "fintech"],
    estimatedMinutes: 15,
    language: "sql",
    pathIds: [BACKEND_PATH, SYSTEM_PATH], moduleIds: [BACKEND_DB], lessonIds: [lessonId(BACKEND_DB, "composite-indexes-query-shape")], confidenceLevel: "warmup",
    prompt: "For `SELECT id,total FROM orders WHERE customer_id=? ORDER BY created_at DESC LIMIT 20`, choose a composite index, explain the column order, and state one write-side cost of adding it.",
    constraints: "Assume many customers and many orders per customer. The database should locate one customer's newest rows without sorting the full table.",
    hints: ["Put the equality predicate before the ordering column."],
    solutionOutline: "Use an index beginning `(customer_id, created_at DESC)`, optionally including selected columns if the database supports covering indexes. It locates the customer range and emits newest entries in order. The cost is extra storage and index maintenance on writes.",
    commonMistakes: ["Leading with created_at and losing the selective customer prefix.", "Saying indexes are free for inserts and updates."],
    followUpQuestions: ["When would a partial index help?", "How would status in the filter change the key order?"],
    rubric: [{ criterion: "Index order", description: "Uses equality-prefix then ordering column with a clear explanation." }, { criterion: "Tradeoff", description: "Names write and storage costs without overcomplicating the warmup." }],
    sourceType: "original", sourceUrls: [], licenseNote: ORIGINAL_NOTE, qualityScore: 4,
  },
  {
    slug: "unique-email-race-warmup",
    title: "Prevent Two Accounts with the Same Email",
    type: "databases",
    difficulty: "easy",
    topics: ["unique-constraints", "transactions", "race-conditions"],
    targetRoles: ["backend_swe", "new_grad_swe", "fullstack_swe"],
    companyStyles: ["startup", "fintech"],
    estimatedMinutes: 15,
    pathIds: [BACKEND_PATH], moduleIds: [BACKEND_DB], confidenceLevel: "warmup",
    prompt: "Two signup requests both run `SELECT` to check that an email is unused, then both insert. Explain why the application check races and identify the database constraint and error-handling behavior required.",
    constraints: "Email normalization must be consistent. Concurrent requests may reach different application instances.",
    hints: ["Let the database arbitrate uniqueness at the write boundary."],
    solutionOutline: "Normalize the email, enforce a unique constraint/index on the normalized value, attempt the insert, and translate a uniqueness violation into the product's conflict response. A pre-check may improve UX but is never the correctness boundary.",
    commonMistakes: ["Protecting the check with an in-memory lock on one server.", "Keeping only the SELECT check and assuming requests are sequential."],
    followUpQuestions: ["How does soft deletion affect uniqueness?", "Should email comparison be case-sensitive?"],
    rubric: [{ criterion: "Race explanation", description: "Shows how both pre-checks can succeed concurrently." }, { criterion: "Database invariant", description: "Uses a normalized unique constraint and handles conflicts explicitly." }],
    sourceType: "original", sourceUrls: [], licenseNote: ORIGINAL_NOTE, qualityScore: 4,
  },
  {
    slug: "ai-debug-prompt-warmup",
    title: "Turn a Vague Bug Report into a Useful AI Prompt",
    type: "ai_usage",
    difficulty: "easy",
    topics: ["prompting", "debugging", "token-efficiency"],
    targetRoles: ["backend_swe", "new_grad_swe", "platform_engineer"],
    companyStyles: ["startup", "big_tech"],
    estimatedMinutes: 12,
    pathIds: [AI_PATH], moduleIds: [AI_PROMPTING], lessonIds: [lessonId(AI_PROMPTING, "token-efficient-debugging-prompts")], confidenceLevel: "warmup",
    prompt: "Rewrite `the API is slow, fix it` into a compact coding-agent prompt containing the observed behavior, expected behavior, inspect-first context, constraints, and validation target. Explain what repository content you would omit initially.",
    constraints: "Do not paste secrets, the whole repository, or unrelated logs. The agent should verify the bottleneck before editing.",
    hints: ["A useful prompt makes success observable and gives a narrow starting point for inspection."],
    solutionOutline: "State the endpoint and measured latency, expected SLO, relevant trace or profile, handler/client/config paths, non-goals, and exact checks. Ask the agent to inspect call sites and report evidence before changing code. Omit generated files, broad logs, and unrelated directories.",
    commonMistakes: ["Making the prompt shorter by removing the acceptance criteria.", "Anchoring the agent to one unverified root cause."],
    followUpQuestions: ["When should you provide more context?", "How do you redact a useful production trace?"],
    rubric: [{ criterion: "Prompt structure", description: "Includes evidence, outcome, context, constraints, and validation." }, { criterion: "Context discipline", description: "Uses progressive disclosure and avoids secrets or irrelevant bulk." }],
    sourceType: "original", sourceUrls: [], licenseNote: ORIGINAL_NOTE, qualityScore: 4,
  },
  {
    slug: "ai-verify-config-option-warmup",
    title: "Verify an AI-Suggested Configuration Option",
    type: "ai_usage",
    difficulty: "easy",
    topics: ["hallucinations", "documentation", "verification"],
    targetRoles: ["backend_swe", "new_grad_swe", "platform_engineer"],
    companyStyles: ["startup", "big_tech", "infra_heavy"],
    estimatedMinutes: 12,
    pathIds: [AI_PATH], moduleIds: [AI_REVIEW], confidenceLevel: "warmup",
    prompt: "An AI suggests adding `enableSmartRetries: true` to a client configuration, but you cannot find that option in the project. Describe the smallest verification sequence before accepting, replacing, or rejecting the change.",
    constraints: "The dependency version is pinned. Do not upgrade just to make the suggestion plausible and do not call the paid service during verification.",
    hints: ["Check the lockfile version, installed exports/types, and official documentation for that exact version."],
    solutionOutline: "Confirm the installed version, search local types/source for the option, consult version-matched official docs, and run typecheck or a minimal configuration test. If absent, reject it and implement only documented behavior. Record remaining semantic assumptions in a focused test.",
    commonMistakes: ["Trusting a confident explanation without checking the installed version.", "Upgrading the dependency and silently expanding scope."],
    followUpQuestions: ["What if the library is dynamically typed?", "When is a transport fake better than a unit mock?"],
    rubric: [{ criterion: "Evidence order", description: "Checks local version and installed API before broad web claims." }, { criterion: "Scope control", description: "Avoids an unjustified upgrade and adds executable verification." }],
    sourceType: "original", sourceUrls: [], licenseNote: ORIGINAL_NOTE, qualityScore: 4,
  },
]);
