import { defineProblems, DOCS_INSPIRED_NOTE, EDU_INSPIRED_NOTE } from "./types";

export const starterDebuggingProblems = defineProblems([
  {
    slug: "outbox-publisher-marks-before-send",
    title: "The Outbox Relay That Silently Loses Events",
    type: "debugging",
    difficulty: "hard",
    topics: ["transactional-outbox", "delivery-semantics", "reliability"],
    targetRoles: ["backend_swe", "distributed_systems_engineer", "infrastructure_swe"],
    companyStyles: ["fintech", "big_tech", "infra_heavy"],
    estimatedMinutes: 35,
    prompt: "An outbox relay selects unsent rows, marks each row sent, publishes to Kafka, and commits its database transaction. During broker latency incidents, downstream services permanently miss a small number of events even though the source transaction and outbox row exist. Diagnose the exact crash window, propose a safe relay order, and define how consumers handle duplicates.",
    constraints: "The database and broker cannot share a distributed transaction. The design must tolerate relay crashes before and after publishing and multiple relay instances.",
    hints: ["Marking sent before the external side effect creates an at-most-once window.", "Publish first, then mark; accept duplicate publication and make claiming plus consumption idempotent."],
    solutionOutline: "A crash after committing sent=true but before Kafka acknowledges makes the row ineligible forever. Reverse the order: atomically claim rows with a lease or SELECT FOR UPDATE SKIP LOCKED, publish with event_id as a stable key, then mark sent only after broker acknowledgement. A crash after publish and before mark republishes, so consumers need an inbox/unique event_id or idempotent state transition. Expired claims recover crashed workers, and monitoring should track oldest unsent age rather than only relay errors.",
    commonMistakes: ["Calling the sequence exactly once without identifying where the cross-system atomicity would come from.", "Publishing first but omitting consumer deduplication, turning a loss fix into duplicate side effects."],
    followUpQuestions: ["How would Kafka producer idempotence help, and what does it not guarantee across relay restarts?", "How should the relay preserve ordering for events belonging to one aggregate?"],
    rubric: [
      { criterion: "Failure window", description: "Identifies the mark-before-publish crash window and its permanent-loss consequence." },
      { criterion: "End-to-end design", description: "Combines safe claiming, publish-then-mark, stable IDs, deduplication, and recovery." },
    ],
    sourceType: "educational_inspired",
    sourceUrls: ["https://microservices.io/patterns/data/transactional-outbox.html"],
    licenseNote: EDU_INSPIRED_NOTE,
    qualityScore: 5,
  },
  {
    slug: "cancelled-request-connection-leak",
    title: "The Connection Pool That Drains After Timeouts",
    type: "debugging",
    difficulty: "medium",
    topics: ["databases", "resource-lifecycle", "cancellation", "observability"],
    targetRoles: ["backend_swe", "infrastructure_swe", "platform_engineer"],
    companyStyles: ["startup", "big_tech", "infra_heavy"],
    estimatedMinutes: 30,
    prompt: "A Go API is healthy after deploy, but after a burst of client cancellations its database pool reaches max-open connections and never recovers. Normal requests then wait until their deadlines. The handler acquires a connection, performs validation that may return early, then defers Close only immediately before the query. Diagnose using pool metrics and repair every exit path.",
    constraints: "The answer should distinguish closing a pooled connection from closing the underlying socket and include a regression test that repeatedly cancels requests.",
    hints: ["List every return between acquisition and the defer statement.", "Acquire and immediately defer release, or use a helper whose lexical scope owns the resource."],
    solutionOutline: "Cancellation exposes an early validation/context return after db.Conn but before defer conn.Close, leaking the checkout. Pool OpenConnections stays capped while InUse rises and Idle falls; wait count and wait duration climb. Move defer immediately after successful acquisition and pass the request context to all queries. Prefer db.QueryContext directly when a dedicated connection is unnecessary. Add a cancellation stress test asserting pool InUse returns to baseline, plus dashboards for acquisition latency and pool state.",
    commonMistakes: ["Increasing MaxOpenConns, which delays exhaustion without repairing ownership.", "Assuming request-context cancellation automatically returns a separately acquired connection to the pool."],
    followUpQuestions: ["How can leaked rows iterators produce the same symptom even when connections are scoped correctly?", "What pool alert separates saturation from a database that is simply handling sustained useful work?"],
    rubric: [
      { criterion: "Metric-driven diagnosis", description: "Uses in-use, idle, wait count, and cancellation correlation to support the leak hypothesis." },
      { criterion: "Lifecycle repair", description: "Places cleanup at acquisition, propagates context, and supplies a regression test." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://pkg.go.dev/database/sql#DB.Stats", "https://pkg.go.dev/database/sql#DB.Conn"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 4,
  },
  {
    slug: "lease-clock-skew-split-brain",
    title: "Two Leaders After the Clock Jump",
    type: "debugging",
    difficulty: "hard",
    topics: ["distributed-locks", "clock-skew", "leases", "fencing"],
    targetRoles: ["infrastructure_swe", "distributed_systems_engineer", "quant_developer"],
    companyStyles: ["infra_heavy", "big_tech", "fintech"],
    estimatedMinutes: 40,
    prompt: "A scheduler uses database lease rows containing owner_id and expires_at based on each worker's wall clock. After an NTP correction, two workers both execute the same portfolio rebalance. Reconstruct how a backward or forward clock step permits overlapping ownership, explain why a longer TTL is insufficient, and redesign the protected write path with fencing tokens.",
    constraints: "Assume pauses and network delays can exceed the nominal lease duration. The downstream store must reject work from stale lease holders.",
    hints: ["A lease only limits time; it cannot revoke code already running after its ownership expires.", "A monotonically increasing token checked by the protected resource converts stale ownership into a rejectable write."],
    solutionOutline: "Local wall-clock comparisons disagree under skew, and a paused holder can resume after another worker acquires the lease. Even with a database clock, the old process may continue issuing writes. Acquire by atomically incrementing a fencing generation and storing expiry using the authoritative database time. Every downstream mutation carries the generation; the resource persists the highest accepted generation and rejects lower ones. Use renewal margins and monotonic clocks for local elapsed-time decisions, but treat fencing as the safety property.",
    commonMistakes: ["Only increasing the lease duration, which changes probability but cannot revoke stale holders.", "Using a random lock token for release safety but not a monotonic fencing value checked downstream."],
    followUpQuestions: ["What if the protected resource cannot store or compare fencing tokens?", "How do session-based coordination services differ from application-managed timestamp leases?"],
    rubric: [
      { criterion: "Concurrency reconstruction", description: "Explains skew, pause, expiry, reacquisition, and overlapping work as a concrete timeline." },
      { criterion: "Safety mechanism", description: "Uses atomic generations and downstream fencing rather than relying on timing alone." },
    ],
    sourceType: "educational_inspired",
    sourceUrls: ["https://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html"],
    licenseNote: EDU_INSPIRED_NOTE,
    qualityScore: 5,
  },
  {
    slug: "reverse-proxy-buffers-event-stream",
    title: "The Live Feed That Arrives in One-Minute Bursts",
    type: "debugging",
    difficulty: "medium",
    topics: ["http", "server-sent-events", "proxies", "buffering"],
    targetRoles: ["backend_swe", "infrastructure_swe", "fullstack_swe"],
    companyStyles: ["startup", "big_tech", "infra_heavy"],
    estimatedMinutes: 30,
    prompt: "A server-sent-events endpoint flushes each update and works when accessed directly, but through the production reverse proxy the browser receives a minute of updates at once. CPU and network are normal, reconnects are rare, and packet captures show bytes leaving the app promptly but not the proxy. Diagnose the buffering layer and propose a production-safe configuration and heartbeat strategy.",
    constraints: "Keep HTTP intermediaries and idle timeouts in scope. Do not disable buffering globally for ordinary responses.",
    hints: ["Compare timestamps at the app socket, proxy upstream, proxy downstream, and browser EventSource callback.", "Streaming routes need proxy buffering disabled and periodic bytes to keep idle connections alive."],
    solutionOutline: "The evidence localizes delay to proxy response buffering: the app flushes chunks, but the proxy accumulates them until a buffer or timeout threshold. Disable proxy buffering only for the SSE location or emit the appropriate no-buffer response header when supported. Preserve text/event-stream, avoid response compression that re-buffers tiny chunks, and send comment heartbeats more frequently than every intermediary idle timeout. Test through the full production path with per-event timestamps.",
    commonMistakes: ["Adding more application flush calls after evidence already shows bytes reaching the proxy promptly.", "Disabling all proxy buffering globally, harming cacheable and high-throughput non-streaming responses."],
    followUpQuestions: ["How do HTTP/2 multiplexing and connection limits change operational behavior for SSE?", "When would WebSockets be a better transport, and which buffering problems would remain elsewhere?"],
    rubric: [
      { criterion: "Layer isolation", description: "Uses timestamped evidence to locate buffering between proxy ingress and egress." },
      { criterion: "Scoped remediation", description: "Configures only the streaming route and addresses compression, heartbeats, and idle timeouts." },
    ],
    sourceType: "official_docs_inspired",
    sourceUrls: ["https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering", "https://html.spec.whatwg.org/multipage/server-sent-events.html"],
    licenseNote: DOCS_INSPIRED_NOTE,
    qualityScore: 4,
  },
]);
